### ISSUE TITLE
Provide an endpoint to view the owner of a token

### ISSUE THREAD

**Issue by mike-engel** [rust-lang/crates.io#1012]
Howdy Crates.io team!

As a dev/publisher on crates.io, I usually want to know who I'm logged in as via `cargo` but have no way to know. npm has something similar with `npm whoami` which helps me make sure that I'm both logged in and logged in as who I think I am before I publish a crate.

I just switched to a new computer, so I couldn't remember if I had logged into cargo yet, which is where this came about. Normally I would make this an issue on the cargo repo (and maybe I will depending on how this goes!) but right now I don't see a way to view who owns a token.

Cargo only stores the token and no user info, so it would be nice to have an endpoint that either returns the name or username of the owner of a token. This probably comes with security concerns, but I think everything on crates.io is public (no private accounts) so maybe it wouldn't be too bad? Also if you already have the token, you can already do a lot of stuff on behalf of the owner. The biggest problem would be guessing/brute forcing the token itself, which again you can already try.

Hopefully this all makes sense and is thorough enough. I'd be happy to provide more use cases or explain things further. If it's an idea y'all like, I'd also potentially be willing to take a stab at a PR (still a rust beginner!). Thanks!

**Comment by carols10cents** [comment]
So I *think* this is already technically possible, but I'd like to make one change before adding it to a cargo command. I just tried this:

```
curl 'https://crates.io/me' -H 'Accept: application/json' -H 'Authorization: mytoken'
```

and got:

```
{"user":{"id":396,"login":"carols10cents","email":"carol.nichols@gmail.com","name":"Carol (Nichols || Goulding)","avatar":"https://avatars2.githubusercontent.com/u/193874?v=4","url":"https://github.com/carols10cents"}}
```

so cargo could parse out the user login value and display that!

The change I'd like to make is to move the `/me` backend routes under `/api/v1` like the other backend routes ([see some discussion here](https://github.com/rust-lang/crates.io/pull/910#issuecomment-318250109), so that they're consistent before cargo is using them and we won't be able to change them forever. 

I *think* it should be straightforward but it has the potential to be hard to track down places that might need to be updated-- so normally I'd offer this to you to fix, but I think it'd be faster for me to do it :) I'm kind of excited this is already mostly done, so I'm going to give this a try real quick :)

**Comment by carols10cents** [comment]
That wasn't too bad-- I've got #1017 open :)

**Comment by mike-engel** [comment]
You're awesome @carols10cents, thanks! I'll keep an eye on that PR and once that's merged in, open a PR in the cargo repo for a `whoami` command 🙂

**Comment by carols10cents** [comment]
Oops! #1017 was merged in (and deployed) a while ago but I forgot to comment & close this. Sorry about the delay, but the crates.io side is ready for this now!

**Comment by mike-engel** [comment]
No worries! I caught it, but haven’t had enough time to make a cargo PR yet. Thanks for the heads up though!
