### ISSUE TITLE
Prerender only max version of crates' readmes, lazily render/cache older versions' as requested

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#1025]
It takes a long time to rerender all the readmes for all the versions on crates.io :( 

I think a way to cut down on this time by a lot is just to render fewer versions upfront, and render the rest on-demand. What I'm envisioning is:

- Change the readme rendering to be proxied through crates.io's backend rather than served from s3 directly. That way, we can check to see if it exists on s3 first, and try and render and serve it if it doesn't (hmmmm we don't want to keep trying to render readmes that are missing over and over, hmmmm)

Once the proxying/request rendering if it isn't on s3 yet, the render-readmes script should:

- Remove all rendered readmes saved on s3
- For each crate, render and save to s3 the readme for the latest version semvertically (that is, whatever version shows up when you go to crates.io/crates/cratename, not necessarily the most recently published version)

As new versions are published, the publish process will render their readme to s3. The next time we need to rerender readmes, old versions will get cleared out.

**Comment by Turbo87** [comment]
while the faster rerendering would be nice, I'm not sure whether that alone is worth the additional complexity and potential performance impact. the rendered readmes are currently served through a globally distributed CDN, but if we routed all those requests through the API we'd increase the latency unnecessarily. the rerendering might be slow but since we don't need it that often I think this is probably fine?
