### ISSUE TITLE
Clean up outdated

### ISSUE THREAD

**Issue by Gedweb** [rust-lang/crates.io#1043]
Vote feature required for outdated packages. Also maybe provide comments for a crate.
Voting results can be used for sorting result on search.

Why:
List of outdated in top search result
https://crates.io/crates/rest
https://crates.io/crates/http
https://crates.io/crates/date

**Comment by carols10cents** [comment]
We are not implementing voting or comments due to the moderation burden it would incur. Please see [the discussion on this RFC](https://github.com/rust-lang/rfcs/pull/1824).

The "Recent downloads" sorting option is meant to help find crates that are recently popular. 

What searches were you doing that these crates came up for?

Also note that [the http crate will soon be getting a new version](https://users.rust-lang.org/t/announcing-the-http-crate/12123).

**Comment by Gedweb** [comment]
No matter how it will be found - crate name busy, but crate abandoned. A moderation burden is not required, it can be just addition info for research.
Count of downloads can't show what crate can be used.

Type "rest" and try found alive crate. You need watch into page of crate and repository, to be sure on it.
Little bit more info about crate is required.

**Comment by carols10cents** [comment]
> A moderation burden is not required, it can be just addition info for research.

Moderation of comments and ratings is required due to the Rust community standards.

> Count of downloads can't show what crate can be used.

Even abandoned crates can be used. Just because there hasn't been development lately, doesn't mean the crate doesn't work.

> Little bit more info about crate is required.

If comments and ratings are the more info that you want, those comments and ratings will also get out of date. If you want commit information in crates.io, that's not available for all crates since a link to the crate's repository is not required.

I'm going to close this since I don't think this is covering any ground that hasn't been covered already in [RFC 1824](https://github.com/rust-lang/rfcs/pull/1824). Thanks!

**Comment by Gedweb** [comment]
Any questions about Rust provide inactivity or resistance from "community" (necessary people with privilegios in primary).
