### ISSUE TITLE
Crates who have yanked all their versions should only return name, owners, and that it's yanked

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#1058]
In search results and on the crate's page, we should be displaying crates with all of their versions yanked (henceforth referred to as "yanked crates") differently (https://github.com/rust-lang/crates.io/issues/145), but the backend needs to tell the frontend that a crate is in this state.

Instructions for fixing this:

- [ ] Add a field named `all_versions_yanked` to [`EncodableCrate`](https://github.com/rust-lang/crates.io/blob/76d15c1a909ddcbf23413a5a3ad477874baca859/src/krate.rs#L106) and everywhere we create `EncodableCrate` instances, set that field to false if there exists any non-yanked versions for this crate. I'd recommend doing a `select(exists())` query using diesel similar to [this query](https://github.com/rust-lang/crates.io/blob/76d15c1a909ddcbf23413a5a3ad477874baca859/src/krate.rs#L244)
- [ ] If we're constructing an `EncodableCrate` instance for a yanked crate, these fields should be changed too:
  - `badges`, `description`, `homepage`, `documentation`, and `repository` should be `None`
  - `max_version` should be `"0.0.0"`

Some other fields, like keywords and categories, are used for search/crate lists, and this issue isn't going to change search results, so I think we should still display why a crate showed up in a particular list of crates.

**Comment by seanlinsley** [comment]
I'd like to work on this. It'll be my first Rust contribution! Thanks for making it so accessible to new people :octocat: ❤️ I actually got here from the RustConf keynote on YouTube.

**Comment by carols10cents** [comment]
Hi @seanlinsley!!! It's awesome to have you!! Please let me know if you have any questions ❤️

**Comment by seanlinsley** [comment]
When running `diesel migration run` I noticed this error:

```
NOTICE:  table "schema_migrations" does not exist, skipping
```

The backend server appears to boot, though some tables are missing when running the tests:
```rust
---- category::tests::category_toplevel_includes_subcategories_in_crate_cnt stdout ----
  thread 'category::tests::category_toplevel_includes_subcategories_in_crate_cnt' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(__Unknown, "relation \"categories\" does not exist")', src/libcore/result.rs:860:4

---- category::tests::category_toplevel_applies_limit_and_offset stdout ----
  thread 'category::tests::category_toplevel_applies_limit_and_offset' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(__Unknown, "relation \"categories\" does not exist")', src/libcore/result.rs:860:4

---- category::tests::category_toplevel_orders_by_crates_cnt_when_sort_given stdout ----
  thread 'category::tests::category_toplevel_orders_by_crates_cnt_when_sort_given' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(__Unknown, "relation \"categories\" does not exist")', src/libcore/result.rs:860:4

---- category::tests::category_toplevel_applies_limit_and_offset_after_grouping stdout ----
  thread 'category::tests::category_toplevel_applies_limit_and_offset_after_grouping' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(__Unknown, "relation \"categories\" does not exist")', src/libcore/result.rs:860:4

---- category::tests::category_toplevel_excludes_subcategories stdout ----
  thread 'category::tests::category_toplevel_excludes_subcategories' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(__Unknown, "relation \"categories\" does not exist")', src/libcore/result.rs:860:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- keyword::tests::dont_associate_with_non_lowercased_keywords stdout ----
  thread 'keyword::tests::dont_associate_with_non_lowercased_keywords' panicked at 'called `Result::unwrap()` on an `Err` value: DatabaseError(__Unknown, "relation \"keywords\" does not exist")', src/libcore/result.rs:860:4


failures:
    category::tests::category_toplevel_applies_limit_and_offset
    category::tests::category_toplevel_applies_limit_and_offset_after_grouping
    category::tests::category_toplevel_excludes_subcategories
    category::tests::category_toplevel_includes_subcategories_in_crate_cnt
    category::tests::category_toplevel_orders_by_crates_cnt_when_sort_given
    keyword::tests::dont_associate_with_non_lowercased_keywords

test result: FAILED. 12 passed; 6 failed; 0 ignored; 0 measured; 0 filtered out
```

The setup instructions say that `cargo test` should run the migrations automatically. Perhaps that's broken?

A caveat was that I ran `diesel migration run` (for the dev env) twice before it ran successfully (because of misconfiguration). Perhaps they modified some global state before exiting?

These were the exact errors:
```sh
# I hadn't set up `.env` yet

$ diesel migration run
The --database-url argument must be passed, or the DATABASE_URL environment variable must be set.

# Homebrew's install doesn't provide a postgres user

$ diesel migration run
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectionError(BadConnection("FATAL:  role \"postgres\" does not exist\n"))', src/libcore/result.rs:860:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by seanlinsley** [comment]
Indeed, the test database has no tables in it.

**Comment by seanlinsley** [comment]
Oddly `diesel migration run --database-url cargo_registry_test` doesn't do anything.

**Comment by sgrif** [comment]
It's a clap bug. https://github.com/kbknapp/clap-rs/issues/978 Unfortunately you need to do `diesel migration --database-url=... run`. Your database URL should probably be `postgres://localhost/cargo_registry_test`

**Comment by sgrif** [comment]
If you have `TEST_DATABASE_URL` set in a `.env` file, just running `cargo test` should migrate it automatically

**Comment by carols10cents** [comment]
> If you have TEST_DATABASE_URL set in a .env file, just running cargo test should migrate it automatically

The trick is that `cargo test` migrates the database *when you compile the tests*, if you had the tests compiled previously, didn't change anything, and reran `cargo test`, that *wouldn't* migrate the test database :(

I'm not sure how to fix the underlying issue, ideas welcome over at https://github.com/rust-lang/crates.io/issues/988. 

In the meantime, @seanlinsley, if you change a test file and run `cargo test`, or alternatively run `cargo clean` and then `cargo test`, does that get the tests to pass? Sorry about the trouble :( :(

**Comment by seanlinsley** [comment]
Sorry for the delay on this; picking it back up today.

**Comment by seanlinsley** [comment]
`cargo clean` indeed worked. I'm not familiar enough with the problem space to suggest a fix.

I didn't delete the database myself like described in #988. I thought I'd seen an exception during the test setup when running `cargo test` for the first time, but that doesn't seem to have been the case...

**Comment by seanlinsley** [comment]
`encodable` should definitely send down this attribute, but what about `minimal_encodable`?

**Comment by seanlinsley** [comment]
It looks like the show action uses `encodable` and the index action uses `minimal_encodable`, so yes they both need to be updated.

Both the show & index actions already load all versions into memory:

https://github.com/rust-lang/crates.io/blob/ef1ac581f9c4ea6a906347d43776418acfdbb8ca/src/krate/mod.rs#L880-L882

https://github.com/rust-lang/crates.io/blob/ef1ac581f9c4ea6a906347d43776418acfdbb8ca/src/krate/mod.rs#L736-L740

So it may be more efficient to construct this attribute in memory, instead of doing another database request.


This should work for the show page:

```rust
let all_versions_yanked = versions.iter().any(|v| !v.yanked).collect();
```

For the index page, I was thinking of updating the existing `versions...map` to also return `all_versions_yanked`, such that the `zip...map` ends up looking like this:
```diff
@@ -744,7 +748,7 @@ pub fn index(req: &mut Request) -> CargoResult<Response> {
         .zip(perfect_matches)
         .zip(recent_downloads)
         .map(
-            |(((max_version, krate), perfect_match), recent_downloads)| {
+            |((((max_version, all_versions_yanked), krate), perfect_match), recent_downloads)| {
                 // FIXME: If we add crate_id to the Badge enum we can eliminate
                 // this N+1
                 let badges = badges::table
```

I'm not totally happy with that though; it seems like that code has a tendency to become more and more nested. I'll also need to learn a bit more Rust to write it 😄

**Comment by seanlinsley** [comment]
Using `select(exists())` was recommended, which would make sense for the index page. I'd usually expect to see that on the main select by joining the versions table, however the main select isn't currently joining other tables:

https://github.com/rust-lang/crates.io/blob/ef1ac581f9c4ea6a906347d43776418acfdbb8ca/src/krate/mod.rs#L602-L615

-------------------

The `summary` route has the same problem of having a lot of custom code to build `max_version`...

https://github.com/rust-lang/crates.io/blob/ef1ac581f9c4ea6a906347d43776418acfdbb8ca/src/krate/mod.rs#L797-L802

I'm tempted to update `encodable` and `minimal_encodable` to accept a vector of versions, instead of vectors of version numbers and `max_version`. That's already the case for keywords, categories, and badges, but not recent downloads.

**Comment by seanlinsley** [comment]
Ah, the problem with that is that the versions already loaded are excluding yanked versions.

Another thing to note is that it's not as simple as `select(exists())` or `.any(|v| !v.yanked)`, since you wouldn't want `all_versions_yanked` to equal true if it's a brand new crate that hasn't released and versions. Or is that not possible?

**Comment by seanlinsley** [comment]
I'm having trouble figuring out how to get `grouped_by` to work with `zip`, so that it'll pass down all versions grouped by a crate.

**Comment by seanlinsley** [comment]
Unsure if the `zip` issue went away because I fixed some type errors, but at least it's no longer a compile error. The only remaining error I have is:
```
error[E0619]: the type of this value must be known in this context
   --> src/krate/mod.rs:360:40
    |
360 |         let max_version = Version::max(versions.into_iter().map(|v| v.num));
    |                                        ^^^^^^^^^^^^^^^^^^^^

```

From this code:
```rust
    pub fn encodable(
        self,
        versions: Vec<Version>,
        keywords: Option<&[Keyword]>,
        categories: Option<&[Category]>,
        badges: Option<Vec<Badge>>,
        exact_match: bool,
        recent_downloads: Option<i64>,
    ) -> EncodableCrate {
        let (versions, yanked_versions) = versions.into_iter().partition(|v| !v.yanked);

        let max_version = Version::max(versions.into_iter().map(|v| v.num));

        let all_versions_yanked = yanked_versions.len() > 0 && versions.len() == 0;
```

Which is odd, because the line right above that doesn't have an issue calling `into_iter`.

**Comment by seanlinsley** [comment]
Ah, I guess the extra call to `into_iter` should be unnecessary because `partition` returns iterators. So the problem might be that I'm reassigning the `versions` variable to a different type (from vector to iterator).

**Comment by seanlinsley** [comment]
Nope, it's still a problem when defining it to a new variable:
```rust
let (live_versions, yanked_versions) = versions.into_iter().partition(|v| !v.yanked);

let max_version = Version::max(live_versions.map(|v| v.num));
```

**Comment by seanlinsley** [comment]
This is the first version I've written that compiles 🎉 
```rust
let (live_versions, yanked_versions): (Vec<Version>, Vec<Version>) = versions.into_iter().partition(|v| !v.yanked);

let live_versions = live_versions.into_iter();

let version_ids = live_versions.clone().map(|v| v.id);
let max_version = Version::max(live_versions.clone().map(|v| v.num));

let all_versions_yanked = yanked_versions.len() > 0 && live_versions.len() == 0;
```
It certainly seems far from optimal, having to call `clone`. I had to do that to get around E0382.

**Comment by hbina** [comment]
Hi, if no one is working on this issue I want to pick it up :3

**Comment by carols10cents** [comment]
Hi @hbina, sorry for the delay in responding, no one is currently working on this that I know of so please feel free if you're still interested!

**Comment by sorcerix** [comment]
Is anyone currently working on this? If not would I be able to take it on?

**Comment by carols10cents** [comment]
I don't know of any work being done on this right now, please go ahead! Let me know if you have any questions!

**Comment by willolisp** [comment]
Hey there! Anyone working on this one right now? Also, would this be a good first issue for someone completely new to the language :)? Cheers!

**Comment by carols10cents** [comment]
@willolisp I don't think there's anyone working on it, and yes, I think this would be a good first issue! Please ask if you have questions, thanks!

**Comment by willolisp** [comment]
@carols10cents cool! Then I'll give this one a try. Thanks so much!

**Comment by hayleyjames** [comment]
Hey 👋

Is anyone working on this at the moment? If not, I would like to tackle this issue.

@carols10cents Assuming I can work on this, should EncodableCrate::from_minimal also support all_versions_yanked?

**Comment by carols10cents** [comment]
@hayleyjames I would expect any progress on this to be shown on the issue or in a connected PR, so it looks like no one is working on this right now!

> Assuming I can work on this, should EncodableCrate::from_minimal also support all_versions_yanked?

Yes, on a quick glance, I think so, because `from_minimal` is used on the search page and that's an important spot we want to use `all_versions_yanked`.

**Comment by hayleyjames** [comment]
@carols10cents Thanks! I'll start working on this.

**Comment by mario-areias** [comment]
Hi @carols10cents I put a PR together for this issue based on the comments from this issue: #5314 

This is my first PR in Rust, so I probably did some silly mistakes 😅 . Let me know what needs to be changed and I will keep working on it :)

**Comment by Turbo87** [comment]
we talked about this situation in the crates.io team meeting last week and decided that we would like to change course on this issue. only displaying reduced information has quite a few downsides (e.g. who do you contact to maybe take over ownership of the crate) and we would prefer to display yanked crates/versions like their unyanked counterparts, but with some sort of banner that makes it very visible that the users is looking at a yanked crate/version.

since this is a significant change to the original issue description I'll close this issue and create a new one, based on the above.
