### ISSUE TITLE
No longer able to log in with github

### ISSUE THREAD

**Issue by Michael-F-Bryan** [rust-lang/crates.io#1077]
I'm wanting to push a new version of one of my crates and found that I can no longer log into crates.io.

When I hit the "Log in with GitHub" button it pops up a new window which goes to the `/github_login` endpoint before being redirected to `/authorize/github?code=XXXXXXX&state=YYYYYY`. The window immediately closes and you get a nice red flash message saying:

```
Failed to log in: invalid state parameter
```

Because I can't login, I'm unable to get an API token and `cargo login` can't proceed.

**Comment by carols10cents** [comment]
Hi @Michael-F-Bryan! I'm really sorry about that-- I'm looking into it right now. 

What operating system and browser are you using, please?

**Comment by carols10cents** [comment]
I've just tried reproducing this on macos in firefox and chrome, as well as on Windows 10 using Edge 15, and on all of these, I'm able to log in successfully. Please do let me know what you're using.

Some other things for you to try:

- Log out of GitHub and then try logging in to crates.io, so that you'll be prompted to log in to GitHub as well

- Go to https://github.com/settings/applications and revoke crates.io's privileges and then try logging in to crates.io, so that you'll be prompted to re-grant permission

**Comment by Michael-F-Bryan** [comment]
This was on Arch Linux and Google Chrome. 

I went back after half an hour or so and found that it had logged me in. It's working fine for me now, but I'm curious why there was the "invalid state parameter" error. Maybe there's a slight difference between what crates.io expects when you sign in with GitHub and what it actually gets?

**Comment by carols10cents** [comment]
We had a [similar problem](https://github.com/rust-lang/crates.io/issues/820) in the past when we tried to use the ember-fetch addon, but that caused the problem for everyone. I'm not sure what would cause the problem to happen intermittently; in order to debug this further we'd need to figure out what was different for you when it was happening :(
