### ISSUE TITLE
MX records for mail.crates.io

### ISSUE THREAD

**Issue by Hoeze** [rust-lang/crates.io#1125]
Hi,
my mail server does not accept your mails from "mail.crates.io", since there are no MX records pointing to mailgun.us:
`Oct 13 15:33:57 *** postfix/smtpd[***]: NOQUEUE: reject: RCPT from rs224.mailgun.us[209.61.151.224]: 450 4.1.8 <bounce+***-***=***@mail.crates.io>: Sender address rejected: Domain not found; from=<bounce+***-***=***@mail.crates.io> to=<***> proto=ESMTP helo=<rs224.mailgun.us>`
Would it be possible to fix this?

**Comment by alexcrichton** [comment]
@carols10cents you said awhile ago that we should set MX records for crates.io, but we couldn't do that due to using emails like help@crates.io on our DNS provider. This looks like it's for mail.crates.io, however, so I wonder if those records should be set for that domain name? (which I believe we can do)

If so, do you know what records I should configure?

**Comment by carols10cents** [comment]
We recently changed our MX settings and our error rate in mailgun has gone way down, so I think this is fixed. Please comment if not!
