### ISSUE TITLE
Render non-markdown READMEs

### ISSUE THREAD

**Issue by AdamNiederer** [rust-lang/crates.io#1223]
Currently, READMEs written in org, rst, tex, or any other markup language aren't rendered on a crate's page.

We could perhaps use a [pandoc](http://pandoc.org/) subprocess to spit out the relevant HTML fragments. I'm not aware of any rust-native libraries with comparable coverage.

**Comment by tshepang** [comment]
Or, tt the very least, just render them as-is (original text). This looks sad https://crates.io/crates/humantime/1.0.0.

**Comment by flying-sheep** [comment]
Yeah! It would be kinda silly to write documentation for my [rST rendering crate(s)](https://github.com/flying-sheep/rust-rst/) in Markdown.

**Comment by Turbo87** [comment]
> Or, at the very least, just render them as-is (original text). This looks sad https://crates.io/crates/humantime/1.0.0.

FWIW https://github.com/rust-lang/crates.io/pull/1134 has addressed this issue. Only markdown files and README files without file extensions are now interpreted as Markdown.

Since documentation comments in Rust only support Markdown I think it's reasonable for us to also only support Markdown. Other formats are now displayed as plain text so basic support exists, but implementing more than that would increase the complexity quite a bit and that doesn't not seem like something we will implement in the near future.
