### ISSUE TITLE
Unhelpful error when publishing crate with long keywords

### ISSUE THREAD

**Issue by killercup** [rust-lang/crates.io#1244]
> error: api errors: invalid upload request: invalid length 22, expected a keyword with less than 20 characters at line 1 column 4008

is not a useful error when publishing a crate that has

```toml
keywords = ["cli", "command-line-interface"]
```

I'm pretty sure the error comes from

https://github.com/rust-lang/crates.io/blob/04ca81016571f3f43f60a97889e38e23e85cc331/src/upload.rs#L160-L161

and a solution would be to either return a D::Error compatible error type that can carry a String with it, or try and validate this in

https://github.com/rust-lang/crates.io/blob/04ca81016571f3f43f60a97889e38e23e85cc331/src/upload.rs#L88-L89

where we might get a better error in context.

A more radical thing to do (which @sfackler suggested on IRC and which I totally agree with) is to pull these validations out of the deserialization and do them in a separate pass, maybe using something like the [validator](https://github.com/Keats/validator) crate.

**Comment by Turbo87** [comment]
it looks like there hasn't been much activity on this, and since the original error message at least mentions that the keyword length is the problem I'll go ahead and close this issue for now. due to backward compatibility with older cargo versions we won't be able to significantly change the API response structure anyway 😞
