### ISSUE TITLE
Using 'Showing stats for' dropdown reset scrollbar

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/crates.io#1275]
Selecting a version from the 'Showing stats for' dropdown causes the scrollbar to be reset to the top of the page. It would be nice if the page remained scrolled to the 'Stats' section after using the dropdown.

While this is a fairly minor issue, it can be somewhat annoying on pages with large READMEs, where where 'Stats' section is below the fold.

**Comment by sgrif** [comment]
I don't think there's any way we can actually "fix" this issue. Ultimately this boils down to some UI confusion. "Showing stats for" actually is navigating you to the page for a new version. We have no way of knowing ahead of time whether the height of that page (mainly determined by the README) will be the same, and going to the top of the page makes the most sense for navigation.

However, the wording of that dropdown strongly implies that it only affects the download stats, rather than the entire page. I'm not sure whether the right answer is to reword that drop down, remove it, or change it to only affect download stats.

**Comment by sgrif** [comment]
Either solution sounds fine.
