### ISSUE TITLE
rust-packs

### ISSUE THREAD

**Issue by necrose99** [rust-lang/crates.io#1396]
similar to crate publish ,  I just care to publish a crate-build if not on the crate.io market. 

offer binaries to crates.io  on profile , offer to crate's  author if not available...  if they dont care then I guess offer under usrname... 

ie **ARM64 , IOT class** ,  RPI Rock64 etc..   cargo-ebuild , etc offer subcomponents and or builds to crates.io , espercally if one large crate ie like firefox etc requires 
so next poor sod can just get bins via cargo install ...  and or libs much faster..  and or if IOT corrupts , can rebuild all that much faster.  
gcc Pre-compiled-headers..  would be a similar idea... 

thus for some newer platforms , build pieces can be crowdsourced.

**Comment by jtgeibel** [comment]
While having a means to share pre-build binaries of crates would be nice, I think there are a lot of practical problems and that this is something that would be best developed and supported by the broader ecosystem of tools and crates rather than build directly into crates.io.  In addition to all the various platforms that can be targeted, rustc has no stable ABI between versions and cargo supports feature flags.  With that alone there are a lot of combinations that can affect the build output.

There is also the distinction between debug and release builds (and any one-off build settings that can be set for a profile).  Then, in my experience, there is different output for all the various *modes* (for lack of a better word) that the compiler can be run in.  So a crate and all its dependencies are rebuilt when I run `cargo check` even if I've already run `cargo build`, `cargo clippy`, and have a build within my IDE using the RLS.

It also looks like rustc is sensitive to the build path.  I just built a project and then move the directory somewhere else, and cargo rebuilt the crate rather than reusing the original artifacts.  Then there are build scripts that can do all sorts of arbitrary things.

Finally, even if all these other issues could be mitigated, there are many potential security implications.  We would want several independent builds that are identical (requiring deterministic builds) to help ensure that malicious binaries aren't being distributed.  Even then, such a system could easily be gamed by uploading the same bad binaries from multiple attacker controlled accounts.

So, unfortunately, while it would be nice to avoid burning CPU cycles when someone else has already built a crate and its dependencies, I just don't think there is a clear path forward on how these issues could be addressed.

I'm closing this issue, because I think this functionality would be best developed out-of-tree, hosted on an unofficial domain, community supported, and explicitly opt-in.  Crates.io could support this effort where needed, for example by providing some kind of badge support (similar to our CI badges) if a crate author wants to advertise the location of pre-build artifacts.  However, beyond such potential integration points I don't foresee crates.io as being in a position to move this concept forward.

**Comment by necrose99** [comment]
No problem,  if rust dose ever get a stable abi, and testing abi then perhaps might be an option to have latter on.

As well if user has ftp site linked, would cost crates.io nothing. 
Ie cloudsmith.io often has free package hosting for foss... else paid..
