### ISSUE TITLE
Manage owners link shows if you have the same username as a deleted github account

### ISSUE THREAD

**Issue by Sogomn** [rust-lang/crates.io#1443]
I removed my GitHub account a while ago because I didn't need it anymore. I didn't think about the fact that I had some crates published.
Now I created it again and tried to access said crates (same email, same username).

While it does (kind of?) recognize me as owner, it does not allow me to modify the crate or publish a new version.

When clicking the avatar (see image below) I get forwarded to my new crates.io site (which shows 0 crates).

![image](https://user-images.githubusercontent.com/40247521/41915048-09b55e84-7955-11e8-90f4-a52d91bd5d7c.png)

**Comment by carols10cents** [comment]
This is intentional-- the way github accounts work, if you delete your account, anyone else can create an account with your abandoned username. This would be a security risk if the new account got access to the crates.

Please email help@crates.io from the email listed as the author on your crates and we'll fix it manually.

**Comment by Sogomn** [comment]
I still think it shouldn't display me as owner.

**Comment by carols10cents** [comment]
It's not really displaying you, it's displaying old you.

**Comment by Sogomn** [comment]
Yeah but the "manage owners" link shouldn't be there. I can click on it and edit the owners aswell but the changes don't get saved.

**Comment by carols10cents** [comment]
Ok, that's a bug.
