### ISSUE TITLE
GraphQL API v2

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/crates.io#1464]
The current API is solely designed for the frontend (and some for Cargo), and is pretty useless for any usage other than them. They also have zero stability guarantees.

Here I propose to add a GraphQL based API, which is known for its flexibility (although somewhat complex), and resolves the N+1 queries problems for some queries (e.g. query to the registry, which is currently done with `crates.io-index`).

Most data structures should be straightforward to expose. [Here](https://gist.github.com/swalkinshaw/3a33e2d292b60e68fcebe12b62bbb3e2) is a guide. The exception is the upload and download APIs, which due to GraphQL's lack of blob handling, should be done with the traditional v1 REST APIs. We can provide links to download URL inside v2 API, however.

**Comment by sgrif** [comment]
> and is pretty useless for any usage other than them

Can you elaborate on why it is useless for anybody else?

> They also have zero stability guarantees.

That's not true. They're versioned for a reason, and intended to be stable. We've had some hiccups in the past but that doesn't mean we intend for them to be unstable.

This is proposing a pretty major rewrite of the API, which needs a pretty strong justification.

**Comment by jtgeibel** [comment]
> Plus, maybe not put "deprecated" on essential APIs that are just not used by the frontend?

Do you have examples of anything using (or looking to use) those routes?  I moved them there because they appeared unused, but I would gladly move them to a `third_party` module to explicitly show that we are supporting these endpoints for external users.

I'm only vaguely familiar with GraphQL, but here are my initial thoughts on potential challenges given our existing codebase:

* There are a few places where I think we may want to improve (or at least review) our base data model first.  In particular, I think there are some fields in the crates table that might be a better fit on the versions table.  (In the past we've had bugs where publishing a backport to an old version ends up overwriting values at the crate level, such as pointing the documentation link to an old location.)  I don't see this as a hard blocker, just that we may want to review some parts of the internal API when deciding how to extend our public API.
* I haven't looked into what the tooling currently looks like for GraphQL to build a Rust backend, or integrate with the Ember frontend.  I'm not sure if the frontend could migrate to a new backend API in piecemeal, or if it would largely need to be ported all at once after the new API implemented all the needed functionality.
* I expect we'll keep the v1 cargo endpoints forever, and we have a [small list](https://github.com/rust-lang/crates.io/wiki/Projects-that-use-crates.io's-API) of known external uses.  As you mentioned, the routes dealing with blobs wouldn't be a good fit for the new API.  It would be nice to have a rough outline of what functionality stays where it is, what functionality would be duplicated long term, and where we expect external functionally could be migrated and the duplication removed in a reasonable timeframe.

**Comment by ishitatsuyuki** [comment]
> There are a few places where I think we may want to improve (or at least review) our base data model first.

Refactoring is good, but as the guide mentions, you shouldn't expose any implementation details in the public API interface. Just query the database multiple times if needed.

> I'm not sure if the frontend could migrate to a new backend API in piecemeal, or if it would largely need to be ported all at once after the new API implemented all the needed functionality.

GraphQL on frontend primarily uses [Apollo Client](https://www.apollographql.com/client). It's framework independent and acts as a global store, so it's much delightful frontend coding experience.

For migration, it's possible to migrate page-by-page. Translating queries shouldn't be hard since it's just describing what the UI need. Handling mutations (applying changes to the local store) may need some effort.

As for Rust GraphQL ecosystem, there is a basic GraphQL implementation so you can build a compatible server. However, there isn't any integration with ORM currently which means you will need to somehow translate GraphQL queries into SQL queries, which is quite painful.

**Comment by sgrif** [comment]
> Also, the API isn't documented, and we have no idea what an endpoint will return unless we try or read the source. 

That's because it's not really intended for public consumption right now. It's intended for use by our frontend and cargo itself. We're slowly moving in the direction of having a public API, but what you're proposing is a *massive* endeavor for something that adds little benefit to the tools currently meant to consume the API.

**Comment by Turbo87** [comment]
since there hasn't been a lot of activity here and the chances of us implementing a GraphQL API any time soon are quite slim I'll go ahead and close this issue for now.
