### ISSUE TITLE
Show snippet of 'description' in reverse dependency list

### ISSUE THREAD

**Issue by ihnorton** [rust-lang/crates.io#1574]
It would be helpful if the reverse dependency list could show a snippet of the `description` in addition to the name, to give some idea of what each rev dep package does. I was looking at reverse dependencies for a few crates to try to find idiomatic code "in the wild" (ex just now: ndarray, nalgebra, and a few similar packages). The purpose of some packages can be inferred just from the name, but for others it can not be.

**Comment by carols10cents** [comment]
Sounds good! What needs to happen to implement this:

- The info for each reverse dependency comes from the `versions` in the `/api/v1/crates/[crate name]/reverse_dependencies` API response: https://github.com/rust-lang/crates.io/blob/a898c389f284af995c2457b504a714ca5f24e32b/src/controllers/krate/metadata.rs#L240
- The `versions` are `EncodableVersion`s, so that struct will need a new `description` field of type `Option<String>` (because crates weren't always required to have a description, there are some crates in production without one). `EncodableVersion` is defined here: https://github.com/rust-lang/crates.io/blob/59a4ca9a2d36827b7fb1f14321de7b679cae10dd/src/views.rs#L183-L204
- Currently, description is stored in the `crates` table: https://github.com/rust-lang/crates.io/blob/a898c389f284af995c2457b504a714ca5f24e32b/src/schema.rs#L305-L310 (there is an argument to be made that `description` should be stored per-version, but that's a separate issue)
- So that means we'll need to add `crates::description` to this query: https://github.com/rust-lang/crates.io/blob/a898c389f284af995c2457b504a714ca5f24e32b/src/controllers/krate/metadata.rs#L227-L231
- And then add it to this `map` to pass it to the `Version` `encodable` method: https://github.com/rust-lang/crates.io/blob/a898c389f284af995c2457b504a714ca5f24e32b/src/controllers/krate/metadata.rs#L234
- And update the `Version` `encodable` method definition to accept the description and put it in the new `EncodableVersion` field: https://github.com/rust-lang/crates.io/blob/a898c389f284af995c2457b504a714ca5f24e32b/src/models/version.rs#L41
- Everywhere else we use `EncodableVersion` will also need to be updated; the compiler errors will figure out where they are for you. If we don't need the crate descriptions in those places (because it wouldn't make sense to display the description in that context, or because we're already displaying the description from the crate record for example), setting it to `None` unconditionally seems fine.
- Display the description on the page; the HTML for each reverse dependency is here: https://github.com/rust-lang/crates.io/blob/a898c389f284af995c2457b504a714ca5f24e32b/app/templates/crate/reverse-dependencies.hbs#L17-L27. See the `crate-row` component for the HTML for the description used in other crate lists: https://github.com/rust-lang/crates.io/blob/a898c389f284af995c2457b504a714ca5f24e32b/app/templates/components/crate-row.hbs#L9-L13. Add any CSS needed; I'm not sure if any will be or not.
- Add backend tests for the reverse dependencies API that check the description is set; the other reverse dependency tests are here: https://github.com/rust-lang/crates.io/blob/a898c389f284af995c2457b504a714ca5f24e32b/src/tests/krate.rs#L1738-L1929
- For any other places that use `EncodableVersion`, add tests that the description is either set or unconditionally `None` as decided upon earlier
- Add an assertion to the frontend test for reverse dependencies that the description appears on the page: https://github.com/rust-lang/crates.io/blob/a898c389f284af995c2457b504a714ca5f24e32b/tests/acceptance/crate-test.js#L126-L134

**Comment by yerke** [comment]
Can I claim this issue?

**Comment by carols10cents** [comment]
Yup!!! Let me know if you have any questions!

**Comment by jarivanmenxel** [comment]
Hi! @yerke, are you still working on this issue? If not, I'd like to claim it.

**Comment by delight-aug** [comment]
This issue should be closed

**Comment by Turbo87** [comment]
Indeed, thanks @delight-aug :)
