### ISSUE TITLE
It's possible to permanently lock yourself out of crate ownership through teams

### ISSUE THREAD

**Issue by DianaNites** [rust-lang/crates.io#1583]
It's possible to lock yourself out of crate ownership by adding a team owner, and then removing yourself. Since teams cannot add or remove owners, there is no way to manage ownership from then on.

I have [several crates](https://crates.io/teams/github:hobbyistrust:owners) affected by this.

**Comment by sgrif** [comment]
I'm interested to hear if folks have thoughts on what the solution should be. Right now I only see two clear answers, both of which are suboptimal

- We prevent the last non-org owner from removing themselves
  - Wanting to declare a crate as owned by an organization and not an individual is perfectly reasonable, and I don't think we should require that there always be a single individual owner
  - We may still end up wanting to go this route for other reasons (orgs don't necessarily have a point of contact we can reach for DMCA issues)
- Allow orgs to manage owners if they are the *only* owner
  - This just changes the problem from "it's possible to lock yourself out" to "it's possible to accidentally give admin rights to an entire org"

**Comment by DianaNites** [comment]
Any update? It'd be nice to be able to fix the ownership on my crates at least.

> * Allow orgs to manage owners if they are the only owner
> 	* This just changes the problem from "it's possible to lock yourself out" to "it's possible to accidentally give admin rights to an entire org"

Well, only an entire team in an org, since you can only add teams right?

The ideal solution is probably to separate "owns crate" permissions from "allowed to publish updates" permissions. Theoretically could be done retroactively, named owners get "owns crate", orgs get "allowed to publish", and from then on people or orgs can be in either group. Just an idea though.

**Comment by natboehm** [comment]
Hello! After talking with @carols10cents I've been working on this one. I went the route of preventing the last non-org owner from removing themselves, by changing [this line](https://github.com/rust-lang/crates.io/blob/master/src/controllers/krate/owners.rs#L119) to be checking against the list of user owners, instead of the entire list of team owners and user owners. I'm having problems compiling the tests - I'm getting an error in [`tests::team::remove_team_as_named_owner`](https://github.com/rust-lang/crates.io/blob/master/src/tests/team.rs#L185), but I'm not really sure what the purpose of the test is or if we still need it.

**Comment by DianaNites** [comment]
And fixing the existing ownerless crates?

**Comment by sgrif** [comment]
Please email help@crates.io to coordinate regaining ownership of your crates

**Comment by smarnach** [comment]
I had a quick look at this issue, and noticed a few problems with the current code.

First, the [current check to avoid removing the last owner](https://github.com/rust-lang/crates.io/blob/09c3715bc319aed68574fc49bc7a6a094c753570/src/controllers/krate/owners.rs#L119) seems insufficient even when all owners are individual users rather than teams. The check tests whether the _original_ list of owners had length 1, but since a request can remove multiple users at once, it is still possible to remove all users. If, say, the crate `mycrate` has the owners `user_a` and `user_b`, we can remove both of them with

    cargo owner --remove user_a --remove user_b mycrate

The check won't prevent this, since the length of the original list of owners is 2, not 1.

Second, error reporting could be improved as well. It appears that the API always returns a 200, even when an error occurs. Errors occurring during owner deletion are not propagated to the frontend, and the frontend simply assumes that the owner was removed. Removing the last owner in the frontend makes it first look like the operation was successful, and only when reloading the page it becomes clear that the owner was not actually removed.

The error reporting seems to be out of scope for this particular issue, but the first mentioned problem is in scope, and will require a small amount of refactoring to get right.

I also looked into implementing configurable permissions, as suggested by @DianaNites. This would require

* some more significant refactoring for the backend, since the [`Owner` type](https://github.com/rust-lang/crates.io/blob/b20b7b4d2a4b5b8da9aec2418ba4cf73e2aa8f78/src/models/owner.rs#L33-L36) currently is not able to encapsulate any information in addition to the `Team` or `User` it wraps.
* API functionality to modify the permissions of existing users, together with checks to ensure there is always at least one user or team with full permissions.
* extensions to the frontend to allow configuring the permissions.
* modifications to cargo to allow configuring the permissions via the command line.
* probably an RFC.

This seems to be too much work to be worth it right now, so I suggest sticking with the plan of disallowing the removal of the last non-team owner, while at the same time fixing the bug mentioned at the beginning of this comment.

**Comment by smarnach** [comment]
I chatted with @sgrif about this yesterday. I will take a stab at this, and we agreed to take the route of preventing to remove the last owner.

**Comment by smarnach** [comment]
Another problem with the API endpoint to manage owners is that it is not wrapped in a database transaction. If removing the first owner in the list succeeds, but removing the second one fails, the endpoint will return an error message, making it _look_ like the operation failed completely, while in fact the first owner in the list was actually removed.

The call should either completely succeed and return a success message, or it should return an error message and have no effect. Any mixed results are confusing and error-prone.
