### ISSUE TITLE
Copyable version on search result page

### ISSUE THREAD

**Issue by TorbenJ** [rust-lang/crates.io#1587]
The usual workflow to get a copyable Cargo.toml entry for a given crate one is required to go through four steps:  
- go on crates.io
- search for a crate
- click on search result entry
- copy Cargo.toml entry  via "Copy to clipboard" button

Oftentimes I know what crate I want to use but don't know the exact name of the crate.  
I really would like to have the "Copy to clipboard" button already on the search result page.

There already is a version badge for each crate on the search result page from what I know so I guess the necessary information should already be available.

**Comment by kornelski** [comment]
BTW, it may be even more convenient to install `cargo-edit`, and then run `cargo add crate-name`. It automatically updates `Cargo.toml` with the latest version.

**Comment by carols10cents** [comment]
I think it would be nice to add just the clipboard icon as a link to copy the search result's Cargo.toml entry to the search results page.

Implementation instructions:

- Extract [the copy-to-clipboard button used on the crate version show page and the associated error markup](https://github.com/rust-lang/crates.io/blob/b2c8e18b161d3d91d7bc1750f8d2a3c385210f71/app/templates/crate/version.hbs#L69-L85) into a [component](https://github.com/rust-lang/crates.io/tree/b2c8e18b161d3d91d7bc1750f8d2a3c385210f71/app/templates/components) so that it can be shared between the crate version show and search result pages. It looks like some rearranging of the HTML will be necessary because the `copy-result` div isn't within the `install` div, but I don't think we should show the whole Cargo.toml text in the search results.
- Change the title/alt text from "Copy to clipboard" to "Copy Cargo.toml snippet to clipboard" so that it's more clear what will get copied (I'm open to a different word than "snippet", it's just the first thing that came to mind)
- Include the new component in the [crate-row markup](https://github.com/rust-lang/crates.io/blob/b2c8e18b161d3d91d7bc1750f8d2a3c385210f71/app/templates/components/crate-row.hbs) (decide where it looks best, I'm open to ideas!)
- Update CSS if necessary
- Manually test that copying works in both locations. I would normally say test that the error handling works in both locations, but seeing as [modern browsers support clipboard.js](https://clipboardjs.com/), testing that would be a burden that's not likely worthwhile.
