### ISSUE TITLE
Add rate limiting to consuming new crates names

### ISSUE THREAD

**Issue by jtgeibel** [rust-lang/crates.io#1600]
In addition to IP rate limiting on the publish endpoint, we could add application level rate limiting to the endpoint such that the creation of new crates is limited.  Users who maintain many related crates are likely to publish many new versions quickly, but are less likely to publish brand new crates in a short period of time.

We could set limits on both a per-user and a site-wide basis.

**Comment by matthewkmayer** [comment]
A data point: [Rusoto](https://github.com/rusoto/rusoto) has releases where we'll publish new crates. We've already hit the rate limit ( https://github.com/rust-lang/crates.io/issues/1643 ) when publishing with a powerful machine.

Examples of rates we publish new crates: Rusoto 0.42.0 had five new crates, 0.41 had two, 0.39.0 had nine.

Eventually the rate of new crates published will go down, but it's a possibility we'll want to publish 32 in a single release ( https://github.com/rusoto/rusoto/issues/436 ).

Hopefully these numbers help when this issue is implemented. 😄 

Once https://github.com/rust-lang/cargo/issues/6714 or something like it is implemented we can use that to throttle back our publishing rates. 👍

**Comment by pietroalbini** [comment]
This is already implemented.
