### ISSUE TITLE
A wide table in the README breaks the layout

### ISSUE THREAD

**Issue by RazrFalcon** [rust-lang/crates.io#1638]
Example: https://crates.io/crates/roxmltree

Chrome 72

![1551280638](https://user-images.githubusercontent.com/725494/53501597-1f4ad400-3ab5-11e9-9d51-ec49b468a60c.png)

**Comment by andyfleming** [comment]
A similar example on https://crates.io/crates/dirs

![Screen Shot 2019-03-11 at 2 50 17 PM](https://user-images.githubusercontent.com/721038/54160529-058e8280-440d-11e9-9b35-ae65710f85de.png)

**Comment by andyfleming** [comment]
A possible solution is to add `word-break: break-word;`.

```diff
 .crate-info .crate-readme table {
     border-collapse: collapse;
+    word-break: break-word;
 }
```

![Screen Shot 2019-03-11 at 2 56 19 PM](https://user-images.githubusercontent.com/721038/54161077-5652ab00-440e-11e9-97b1-746f4895b495.png)

Without changing the layout, we could also decrease the font size and padding to make it a little bit more readable.

```diff
 .crate-info .crate-readme table {
     border-collapse: collapse;
+    word-break: break-word;
+    font-size: 14px;
 }

.crate-info .crate-readme table td, .crate-info .crate-readme table th {
    border: 1px solid #dfe2e5;
-    padding: 6px 13px;
+    padding: 3px 6px;
}
```

![Screen Shot 2019-03-11 at 3 03 31 PM](https://user-images.githubusercontent.com/721038/54161265-dc6ef180-440e-11e9-98c3-e4fc5bb5d4a8.png)

I'm not sure it's the ideal solution, but it may be a good short-term fix.

**Comment by hbina** [comment]
Hello! I would like to work on this.
So I think what I have to do is to find the place where crates place the CSS stuff and sneak in the changes @andyfleming suggested?
Any pointers are appreciated.
Thanks!

**Comment by hbina** [comment]
I have clone and set up my mirror of crates.io here https://akarin-crates.herokuapp.com/ but its empty, do i have to manually publish crates that I want to test out. Or did I do something wrong?

**Comment by smarnach** [comment]
@hbina Thanks for looking into this issue!

I can't tell you exactly what way of fixing this works best. Reducing the padding looks fine to me, but I personally wouldn't reduce the font size, nor introduce line breaks in the middle of words, since they make the table very hard to read. `overflow-x: auto` looks like the best option to me – while nobody likes horizontal scrollbars, it seems less bad than all the other options. You can combine this with reducing the padding, thought that is a matter of taste.

It is completely expected that a new installation on Heroku starts with an empty database. You can [upload an affected crates as described in the contribution guidelines](https://github.com/rust-lang/crates.io/blob/master/docs/CONTRIBUTING.md#publishing-a-crate-to-your-local-cratesio). However, since you are only making changes to the frontend, it would be easier for you to [run the frontend locally using the live crates.io server as backend](https://github.com/rust-lang/crates.io/blob/master/docs/CONTRIBUTING.md#building-and-serving-the-frontend), so you can test it with all crates that are currently online. During code review, we will test it on our local installation, so we don't need a publicly accessible staging environment.

**Comment by hbina** [comment]
@smarnach Hi, thanks for the reply. I didn't know you can set it up locally with the actual server as backend. That's a great tip. I will report back as soon as I tested it.
