### ISSUE TITLE
Design mock-up

### ISSUE THREAD

**Issue by azerupi** [rust-lang/crates.io#164]
Hi, 

It's not very clear who is working on crates.io right now and if there are changes planned, like a redesign. 

I think Crates.io can greatly benefit from a redesign, and this has probably been discussed a hundred times already, so my apologies if this post is redundant.

I made a simple mock-up. I haven't invested a lot of time in it, because I first wanted to know if someone is already working on a redesign. And I wanted to get some feedback to see what people like and dislike in the design (both the current and my mock-up).

![image](https://cloud.githubusercontent.com/assets/7647338/8454755/20f3ed4c-2000-11e5-88a9-b1b401c170bf.png)

- The main way of finding Crates is via `search`. Therefore I like the big search bar from my mockup compared to the current one.
- My mock-up is almost monochromatic, a little too much. It would be great if there was an official color scheme (both for rust and crates.io).

**Note:** This is definitely not a finished design and is not meant to be, look at it like some ideas to discuss about and eventually build upon. Take that into consideration when criticizing ;)

**Comment by steveklabnik** [comment]
Hey @azerupi,

While it is true that our web properties could use a fresh coat of paint, we're in the very, very beginning stages of considering what that might be like. we'd like to make some functional and content improvements to several of our web sites, but we're currently at the stage of 'organize our thoughts about what should be on the site,' which is before any design can even happen at all.

The core team hopes to have something more to say on the topic soon, but we don't want to commit to anything publicly right now, as we're not sure what the final form of this effort will be.

If anyone else wants to chime in on this particular mockup, feel free, but since this isn't a bug, I'm going to close it.

**Comment by azerupi** [comment]
Sure, no problem.
Is there an official place where this is discussed? Not necessarily to participate but at least keep up with what is decided and how it progresses? :)

**Comment by steveklabnik** [comment]
not yet, but once it opens up we'll let everyone know.

**Comment by azerupi** [comment]
Ok :) thanks!

**Comment by Turbo87** [comment]
@steveklabnik any news on this?

**Comment by softprops** [comment]
I'd like to add some user feedback. That mockup looks great. One think I hope we wouldn't lose in a redesign is the current color scheme branding. I love it so much.

**Comment by Anachron** [comment]
Isn't this npms website with a different logo?
