### ISSUE TITLE
Enforce that external URIs in crate metadata must be absolute

### ISSUE THREAD

**Issue by nagisa** [rust-lang/crates.io#169]
[core-utils](https://crates.io/crates/core-utils) crate didn’t specify URI scheme when defining its repository link, therefore it is interpreted as `https://crates.io/github.com/0X1A/core-utils`. This can lead to various issues by crafting malicious URIs to achieve unintended actions on crates.io system (trivial example would be following a package).

**Comment by carols10cents** [comment]
What could we normalize the URIs to, though? I think publishing should reject non-absolute URIs instead...

**Comment by kzys** [comment]
+1 for rejecting non-absolute URIs.

**Comment by carols10cents** [comment]
Instructions for implementing this:

- In the [`parse_new_headers`](https://github.com/rust-lang/crates.io/blob/a898c389f284af995c2457b504a714ca5f24e32b/src/controllers/krate/publish.rs#L217) function that interprets the crate metadata sent with a publish request, check the [`EncodableCrateUpload`'s](https://github.com/rust-lang/crates.io/blob/a898c389f284af995c2457b504a714ca5f24e32b/src/controllers/krate/publish.rs#L227) [`homepage`](https://github.com/rust-lang/crates.io/blob/a898c389f284af995c2457b504a714ca5f24e32b/src/views/krate_publish.rs#L23), [`documentation`](https://github.com/rust-lang/crates.io/blob/a898c389f284af995c2457b504a714ca5f24e32b/src/views/krate_publish.rs#L24), and [`repository`](https://github.com/rust-lang/crates.io/blob/a898c389f284af995c2457b504a714ca5f24e32b/src/views/krate_publish.rs#L33) fields for valid, absolute URLs by parsing them with the `url` crate's [`parse` function](https://docs.rs/url/2.1.0/url/struct.Url.html#method.parse).
- I think it would be nice to report all invalid URLs at once, so rather than saying "your repository url is invalid", then they fix that and get "your documentation url is invalid" etc, gather the fields that have invalid URLs and return one error that says "the following fields have invalid URLs: repository, documentation, homepage". This'll look similar to the required field checks here: https://github.com/rust-lang/crates.io/blob/a898c389f284af995c2457b504a714ca5f24e32b/src/controllers/krate/publish.rs#L234-L252
- I'm torn on whether we should somehow report differently on the different [`ParseError` variants](https://docs.rs/url/2.1.0/url/enum.ParseError.html) or whether the error message should say something like "the following fields have invalid URLs: [...] URLs must be absolute and contain valid hosts, ports, and IP addresses when specified" or something similar like that, that prints the same guidelines for any problems. I leave that decision up to whoever implements this :)
- Add tests similar to [the test for author, license, and description being required](https://github.com/rust-lang/crates.io/blob/a898c389f284af995c2457b504a714ca5f24e32b/src/tests/krate.rs#L1931-L1979) that valid URLs are accepted and invalid URLs are rejected.

Bonus: make an executable in `src/bin` that I can run on production that loads each crate record, parses these three fields as URLs, and reports what fields on what crates currently have invalid URLs so that I can fix any existing problems :)

**Comment by carols10cents** [comment]
I... just discovered that [we already do this](https://github.com/rust-lang/crates.io/blob/21e04f3028624485621d577359008560728a37d3/src/models/krate.rs#L132-L161), but in the krate model, not where I was expecting to find this code at all, oops!

... and [that code appears to have existed since 2014-10-08](https://github.com/rust-lang/crates.io/commit/e67560df24ea54b51c49acc1ad3c99a9bd57b219#diff-7ab30501521c288e1d8e1e994692b1a2R117-R137), months before this issue was filed??? how did this even happennnnn

**Comment by nagisa** [comment]
My initial reaction is that perhaps crate might have been uploaded before that commit went live, but this crate was released in April 2015…

Weeeeeeeird.

**Comment by jtgeibel** [comment]
I don't think that existing code enforces an absolute URL.  I'm assuming that you're looking at the call to `url.cannot_be_a_base()`, but the docs there say:

> Return whether this URL is a cannot-be-a-base URL, meaning that parsing a relative URL string with this URL as the base will return an error.
> 
> This is the case if the scheme and `:` delimiter are not followed by a `/` slash, as is typically the case of `data:` and `mailto:` URLs.

I think `url.has_authority()` is probably what we are looking for here.  This function checks that the URL consists of a scheme, followed by `://`.

**Comment by carols10cents** [comment]
I was looking at `Url::parse`, which has a `RelativeUrlWithoutBase` error variant. I was also assuming that the original problem was a URL specified like `github.com/rust-lang/rust`, without a scheme at all, which does return `RelativeUrlWithoutBase`.

However, the problem with the crate in the original issue was that there was a missing forward slash, so the URL specified looked like `https:/github.com/rust-lang/rust`. This [parses successfully](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4b4767598977c16fef862d7fbe74c4a0) with url 2.1.0!!! And `has_authority` returns true!!!

I did a search in a recent production snapshot for repository, documentation, and homepage links that are not null and `NOT SIMILAR TO 'https*://%'`. I found the [hilite](https://crates.io/crates/hilite) crate whose homepage starts with a space, and the [noise_search](https://crates.io/crates/noise_search) and [syntaxdb](https://crates.io/crates/syntaxdb) crates whose homepages have the same missing slash typo. 

Interestingly, both Firefox and Chrome are doing some corrections:

- The space in front of the hilite crate's URL doesn't cause any problems and the link functions as I'd expect in both browsers
- For noise_search, the URL specified is `http:/noisesearch.org` and it gets interpreted by both Firefox and Chrome as an absolute URL
- For syntaxdb, the URL specified is `https:/github.com/orhanbalci` and it gets interpreted by both Firefox and Chrome as the relative URL `https://crates.io/github.com/orhanbalci`! So HTTPS vs HTTP seems to make a difference???

I'm going to take this over to the URL crate I think.

**Comment by carols10cents** [comment]
oh no... trying to read the spec... brain hurts... https://url.spec.whatwg.org/

**Comment by jtgeibel** [comment]
> However, the problem with the crate in the original issue was that there was a missing forward slash, so the URL specified looked like https:/github.com/rust-lang/rust. This parses successfully with url 2.1.0!!! And `has_authority` returns true!!!

I'm super confused by this.  The implementation for `has_authority` is literally this:

```rust
self.slice(self.scheme_end..).starts_with("://")
```

Are you sure it is returning true for a URL missing the 2nd slash?  The current call to `cannot_be_a_base` only checks for a single slash and seems to be the problem.  I think we just need to call `has_authority` instead.

> * For noise_search, the URL specified is http:/noisesearch.org and it gets interpreted by both Firefox and Chrome as an absolute URL
> * For syntaxdb, the URL specified is https:/github.com/orhanbalci and it gets interpreted by both Firefox and Chrome as the relative URL https://crates.io/github.com/orhanbalci! So HTTPS vs HTTP seems to make a difference???

My *guess* is that the first one is being treated differently because the scheme has changed (relative to our HTTPS scheme).  So the browsers treat it differently than the case where the URL is relative and has the same scheme (scenario 2).  It's kind of opposite the behavior of [`protocol-relative`](https://www.paulirish.com/2010/the-protocol-relative-url/) URLS, like `//example.com/path`, which would retain the scheme from the site where the link was clicked but is an absolute URL on another domain/authority.  (Our current explicit check of the scheme already guards against this anti-pattern.)

**Comment by jtgeibel** [comment]
Okay, yeah, `has_authority` doesn't work the way I expected for HTTP/HTTPS URLs.  This URL is false "unix:/example.com/path", but "https:/example.com/path" is true. huh?

It seems like HTTP and HTTPS result in some normalization as they are parsed, adding in the "missing" slash, causing `has_authority` to then be true.

**Comment by kzys** [comment]
@jtgeibel 

> It seems like HTTP and HTTPS result in some normalization as they are parsed, adding in the "missing" slash, causing has_authority to then be true.

Yes.

https://github.com/servo/rust-url/blob/0e874ddcd6fc68a19dc2b6d91bbde2928bac2d0f/src/lib.rs#L658

**Comment by jtgeibel** [comment]
@kzys, yes, but the behavior that is confusing is that parsing the URL causes one to be normalized and the other not.  Based on the implementation, I expect both examples to return false, because neither source string has "://".

**Comment by kzys** [comment]
I think (not fully tested) the url crate is aware about all violations and even corrects them, but by default not reporting them.

https://github.com/servo/rust-url/blob/f491cb442edab75be54ff5961af6458a474f1f9a/src/lib.rs#L365

**Comment by jtgeibel** [comment]
I've opened #1898 that should fix this.  I expect there is some way to get `Url::parse` to work, but for now I've opted for an explicit check of the prefix.  This will also disallow the example that began with a space character.

I still make the call to `Url::parse` to ensure the rest of the URL parses correctly.

**Comment by smarnach** [comment]
While the URL spec does not allow relative URLs to include a scheme, browsers have traditionally allowed this, and keep allowing it for backwards compatibility. I agree that we should only URLs starting with "http://" or "https://", and @jtgeibel's PR looks like the most readable way to achieve that.
