### ISSUE TITLE
Replace access tokens with public keys

### ISSUE THREAD

**Issue by SoniEx2** [rust-lang/crates.io#1723]
By generating a private key on the client and sending the public key to the server, we can prevent someone from stealing the private key and messing with my crates.

I mean, I haven't touched crates.io in *forever*, it would've been plenty of time for someone to do serious damage if they had stolen the DB or something.

even if they had read-only access to the DB they could've gotten plenty of tokens.

tokens are bad!!!! please switch to public keys today!!!! it also prevents "prying eyes"!!!!

**Comment by sgrif** [comment]
This isn't something we can just do on crates.io, as it requires significant changes to Cargo. Since this is a pretty major change that affects user workflows and would require coordination across multiple teams, it will need an RFC in order to happen. I'm going to close this for now, as there's nothing we can do until this goes through the RFC process.
