### ISSUE TITLE
cargo publish README.md with non-https links

### ISSUE THREAD

**Issue by frehberg** [rust-lang/crates.io#1849]
Browsing at https://crate.io the project "test-generator-utest" (ver 0.1.2) the browser firefox shows me a warning "mixed content"; AFAICS, the majority of document-transfers are using https-transport, but some documents are transferred using plain http. Just,Firefox (and other browsers) demand a pure, secure HTTPS transfer.

https://crates.io/crates/test-generator-utest

# Observation

AFAICS, the ffiles belonging to the crates.io web-framework are transferred using HTTPS, but some files belonging to the package "test-generator-utest" are causing the plain HTTP transfer.

The Cargo.toml of the package is referencing a README.md and this contains the plain http links, for example the following plain HTTP link, generating a license-icon.

http://img.shields.io/badge/license-MIT-blue.svg

# Counter Measure

All content of crates.io should use the transport HTTPS, so that browsers do not show security-warnings due to mixed-content. It should not be possible to inject plain-HTTP links into the overall crates.io-framework via README.md or similar files.

Therefore Cargo-publish (uploading a package to crates.io) should not permit plain HTTP-references in README.md  or other doc-files. In those cases the publication should be refused.

**Comment by ehuss** [comment]
I have transferred this to crates.io, as I think it is more relevant there in terms of readme processing. Cargo doesn't have a markdown parser, and I would prefer to avoid adding one.  

I don't actually know of a solution for this, though I would be curious what other package registries do.

**Comment by smarnach** [comment]
The HTML in the README is sanitised, and the only allowed HTML tags that can result in plain-HTTP queries are `<img>` tags. This is also the issue with the mentioned page – the `src` attributes for the badges are plain HTTP links (which incidentally immediately redirect to HTTPS, so the fix for this particular crate would be trivial).

The easiest possible remedy is to remove images with a plain-HTTP `src` attribute during HTML sanitization.

GitHub proxies plain-HTTP images through [Camo](https://github.com/atmos/camo). Maybe we could somehow leverage this infrastructure and use the Camo links as well, at least for crates that are hosted on GitHub.

**Comment by sgrif** [comment]
I don't really think there's any actionable item here. The content is being transferred over HTTP because the README links to an image served over HTTP. It's desirable for folks to ensure their READMEs don't have HTTP links in them, but I don't really see a rationale for rejecting them.

**Comment by smarnach** [comment]
I guess the main reason for us to fix this is so people don't get distracted by a mixed content warning in their browser, and instead get on with what they were actually planning to do. :)

More seriously, allowing plain HTTP images increases the attack surface users are exposed to. They are not a vulnerability by themselves, but together with bugs in image libraries and insecure networks they may contribute to making a vulnerability exploitable. This is the reason why browsers issue warnings for mixed content in the first place. We can with some legitimacy take the standpoint that this isn't our fault, but preventing this on our end is also a valid point of view in my opinion.

**Comment by frehberg** [comment]
@smarnach that is the point

**Comment by sgrif** [comment]
Right, I am in agreement that folks having HTTP images is worse than them having HTTPS. I'm just not sure that there's a solution that we can reasonably implement right now. Stripping the images is confusing at best, and IMO is an over-reaction to the problem. We could do something like what GitHub currently does, and download the images so we can rehost them on our own hardware, but that doesn't seem like something we can reasonably prioritize any time soon.

**Comment by frehberg** [comment]
AFAICS, it those plain-links can't be blocked, maybe it would help to communicate the issue, for example printing a notice to console during upload, or sending an email to the maintainer of the crate, This notice could communicate the issue,  telling that the plain-link in their README will cause warnings in browsers.  asking them to use HTTPS-links instead.

**Comment by smarnach** [comment]
I agree that completely blocking HTTP images is a step too far, but there are other options to explore, e.g. using [Github's markdown API](https://developer.github.com/v3/markdown/) instead of rendering the readme files ourselves. This would give us access to the Camo proxy for free, but there are probably other problems with that approach. (Note that the proxy may still issue a plain HTTP request to the actual image, but this is less bad than the having the browser directly send plain HTTP.)

I suggest we leave this issue open until we have time to explore the solutions.

**Comment by Turbo87** [comment]
I tend to agree with @sgrif that this is not something we can tackle at the moment. Since there hasn't been any activity here for a while I'll close this issue for now. If you really want these things fixed then I would suggest contacting the authors of the corresponding crates. Other than that maybe cargo could warn about HTTP image URLs during upload or something like that.
