### ISSUE TITLE
Searching for image doesn't show imageproc in first 15 pages

### ISSUE THREAD

**Issue by mark-summerfield** [rust-lang/crates.io#1850]
If I search Cargo for 'imageproc' the crate is correctly listed first.
But if I search for 'image' imageproc doesn't appear in the first 15 pages (I didn't look further). This makes it hard to discover. Also, it seems strange because some other crates that begin with 'image' appear on the first page.

**Comment by smarnach** [comment]
The search for "image" currently yields 1066 results, so most of these results won't appear on the first 15 pages. (For what it's worth, `imageproc` currently appears on page 19.)

The default sort order for the search results on crates.io is by "relevance", which uses the following order:

1. A crate that exactly matches the search term comes first.
2. After that, the remaining crates are ranked by a full-text search over the crate name, the keywords and description fields from `Cargo.toml` and the contents of the readme file.
3. Crates with identical rank are ordered by name.

You can also take a look at [the SQL trigger that determines the ranking of the full-text-serach](https://github.com/rust-lang/crates.io/blob/master/migrations/20141020175650_dumped_migration_76/up.sql) and [the code that actuall performs the query](https://github.com/rust-lang/crates.io/blob/12c64bc716a4a7d1fd25f2a658f80cbdcbdcbf08/src/controllers/krate/search.rs#L76-L79).

I'm not quite sure what the request here is. The implication seems to be that `imageproc` is more important than the crates that currently higher, so it should rank higher in the search results. The current ranking algorithm probably has room for improvement, and we welcome specific proposals how to improve it. I will close this issue, though, since it is not actionable in its current form.
