### ISSUE TITLE
SVGs from GitHub aren't rendered correctly in README

### ISSUE THREAD

**Issue by raftario** [rust-lang/crates.io#1851]
By default, GitHub serves raw SVGs with the `Content-Type` header set to `text/plain`, which prevents the images from being displayed properly. This can be fixed easily by adding `sanitize=true` to the query string.

GitHub does it automatically when rendering READMEs, so the issue isn't present on their side and it might be a good idea to replicate that behaviour. (https://github.com/raftario/licensor vs https://crates.io/crates/licensor)

The fix is pretty trivial so I plan to open a PR for it tomorrow.

**Comment by keturn** [comment]
Just noticed this, started looking in to it, and am pleased to see here you've already fixed it!

Which makes me wonder why I'm still seeing it on some crates.

I guess maybe this rendering only happens when the crate is published, so releases from before this change won't have the corrected URLs in them?

**Comment by carols10cents** [comment]
@keturn you're exactly right. We have a script that can rerender READMEs, I'll run it to fix the older READMEs soon :)
