### ISSUE TITLE
Make API key more easily available after creating a new account

### ISSUE THREAD

**Issue by Gankra** [rust-lang/crates.io#19]
Not very discoverable, especially since this is probably the first thing you're interested in getting after registering. Resetting it should definitely be in there, but that's certainly not where I would expect to go for "what is my API key".

Possible solution: redirect new logins and/or registrations to there.

**Comment by carols10cents** [comment]
What happens today when you're a new user of crates.io:

You visit crates.io and see this:

<img width="1016" alt="crates.io homepage" src="https://user-images.githubusercontent.com/193874/68893893-1ad25400-06f4-11ea-96d8-6c376b4952a7.png">

So you click "Log in with GitHub", do the oAuth dance, and you're taken... back to the homepage, only now your icon is in the upper right:

<img width="1003" alt="crates.io homepage but logged in" src="https://user-images.githubusercontent.com/193874/68894160-b368d400-06f4-11ea-81ba-3a04de5600c1.png">

There's not really a call to action, you have to notice there's a little triangle next to your icon that opens this menu:

<img width="1006" alt="user menu open" src="https://user-images.githubusercontent.com/193874/68894057-769cdd00-06f4-11ea-9f54-a527083c46d0.png">

and the menu item you want is "account settings", which is the crates.io/me page where you can verify your email and create API tokens:

<img width="1000" alt="account settings page" src="https://user-images.githubusercontent.com/193874/68894120-9f24d700-06f4-11ea-8c25-fc71f53aeeb4.png">

The smallest change is probably adding a notice at the top of the page that says something like "Welcome to crates.io! Visit [account settings](https://crates.io/me) to verify your email address and create an API token!". 

Ideally, we'd only show that if we just created an account rather than updating one in the [`NewUser` `create_or_update` method](https://github.com/rust-lang/crates.io/blob/21e04f3028624485621d577359008560728a37d3/src/models/user.rs#L55). I *think* we can send that info to the frontend [here](https://github.com/rust-lang/crates.io/blob/21e04f3028624485621d577359008560728a37d3/app/routes/github-authorize.js#L22-L23) from [the backend controller action associated with `/authorize`](https://github.com/rust-lang/crates.io/blob/21e04f3028624485621d577359008560728a37d3/src/controllers/user/session.rs#L46-L105).


Other changes I could see that seem more complex:

- Always redirecting to /me after logging in (not sure if that's the best experience either)
- Customizing the message shown based on whether the user needs to verify their email, create an API token, or both (account completion percentage sort of?)
- Always showing a notice on every page until the user verifies their email and creates an API token, could be annoying

I'm open to thoughts based on what people think the best experience would be and what seems possible/easy to implement!

**Comment by Turbo87** [comment]
These days, cargo tells you to go to https://crates.io/me to create an API token. If you do that without being logged in it shows a page like this:

<img width="669" alt="Bildschirmfoto 2024-01-29 um 10 48 40" src="https://github.com/rust-lang/crates.io/assets/141300/a614c3c4-3749-4438-bd45-ee52370907d1">

If you press the "Login" button/link it will perform the login flow and afterwards direct you to the API tokens settings page where you can create your API token.

It seems to me like this covers most of the discoverability issues here. Let me know if you think that there is more that we can do :)
