### ISSUE TITLE
Clean up the unused version_authors.user_id column

### ISSUE THREAD

**Issue by smarnach** [rust-lang/crates.io#2056]
We can consider removing it from the database schema.

**Comment by carols10cents** [comment]
Yep, looks like [we talked in this PR's comments](https://github.com/rust-lang/crates.io/pull/571) about doing that but never did 😂 

Implementation instructions:

- Create a diesel migration by running `diesel migration generate` and make it drop the `user_id` column on the `version_authors` table. Nothing has ever inserted any values into this table (I checked in production and all rows have `NULL`)
- Commit the schema changes made by running the migration, which should include removing [these lines](https://github.com/rust-lang/crates.io/blob/8cdaa9bc4ebe50479f4fefec6490da2b0e214f67/src/schema.rs#L807-L812) and [this line](https://github.com/rust-lang/crates.io/blob/8cdaa9bc4ebe50479f4fefec6490da2b0e214f67/src/schema.rs#L1029)
- Remove [this line in the database dump config](https://github.com/rust-lang/crates.io/blob/8cdaa9bc4ebe50479f4fefec6490da2b0e214f67/src/tasks/dump_db/dump-db.toml#L182)
- Remove the [empty `users` key from the /authors JSON](https://github.com/rust-lang/crates.io/blob/8cdaa9bc4ebe50479f4fefec6490da2b0e214f67/src/controllers/version/metadata.rs#L48-L61). This has never returned any values, so I highly doubt anyone will break because of this, they should be ignoring this field.
- Fix any compiler or test errors
