### ISSUE TITLE
Idea: Move 'Dependent crates' link nearer to 'Dependencies' section to make it easier to find

### ISSUE THREAD

**Issue by jrajav** [rust-lang/crates.io#2075]
The 'Dependent crates' link is far removed from the 'Dependencies' header / section, and with its muted styling to boot, it's a little bit hard to find. Acknowledging that the 'Dependent crates' page requires an expensive query and can't be an inline section like 'Dependencies', it could still be made easier to discover by placing the link nearer to 'Dependencies'.

![unknown](https://user-images.githubusercontent.com/2074135/71530557-e1beff00-28af-11ea-9252-d2ad1a184656.png)

![unknown (1)](https://user-images.githubusercontent.com/2074135/71530561-e4b9ef80-28af-11ea-9fba-f346e0db0825.png)

**Comment by carols10cents** [comment]
I'd be fine with adding another link to dependent crates closer to the dependencies section in the sidebar; I wouldn't want to remove the link from its current location for people who are used to it being there.

**Comment by steffahn** [comment]
A change like the one proposed here seems to have happened in #3226.

I find this change pretty unfortunate because:

* I second the opinion of @carols10cents that this is bad UX for people who are used to the link being at its old position. It took me personally multiple minutes to find the link at it’s new position, in particular
* I disagree with the sentiment of @Turbo87’s first sentence in the PR which implies that this change would make the link easier to find.
    > In the quicklinks section at the top the link is a bit hard to find.
    
    The new position is _way harder to find_ than the previous one. Especially since, once you know about the quicklinks section, you’ll find out about dependent crates very easily.
* IMO the link is very misplaced at the bottom of the “Dependencies” list. It shared the style of the “show all” button of the “Versions” section. Following this logic
  * one might think that this button does nothing more than show all dependencies (as opposed to _reverse_ dependencies)
  * in particular, it’s styling is very _**small**_ and _**greyed out**_
  * it visually appears to be _part of the dependencies list_. It isn’t! Reverse dependencies are not dependencies so they don’t fall under this heading. In particular, reverse dependencies shows all (reverse) ordinary and dev-dependencies. So it doesn’t make _**any**_ sense whatsoever to link them under “Dependencies”. Also in general, even if you don’t interpret the link as _part of_ the “Dependencies” section, it’s weird to have it _between_ “Dependencies” and “Dev-Dependencies”
* To suggest a different (and actually logical) place for a reverse dependencies link, following the logic already in place on [lib.rs](https://lib.rs)
  * Under the usage statistics would make a lot of sense
  * The actual _reason_ I’m usually looking up reverse dependencies is to find out how much and by whom a library is used, so it fits perfectly
  * This could even become a stat, i.e. number of reverse dependencies / number of crates using this crates. Somewhere near this number should then be a link to the dependent crates. And IMO it doesn’t even _need_ to be the only link.
* I’d also like to point out scrolling. To read the reverse dependencies I now have to scroll down. Scroll down _just_ the right amount to see dependencies, then perhaps some further if the list is long, spot this tiny little link at the end and click it. IMO this is bad UX in general, not just for experienced users that expect the button in the quicklinks section.
  * If a “dependent crates” link is eventually only under statistics, one could help avoid scrolling by providing an intra-page link for quickly jumping down to the statistics section. This helps for crates with long description. On mobile, one might also want a link like this for jumping to where the “sidebar” starts.
* Since adding this properly to the statistics section isn’t trivial, in the meantime I would be very happy if the original link in the “quicklinks section” was restored

### Screenshot of status quo (sidebar, example: `tokio` crate):
![Screenshot_20210210_160158](https://user-images.githubusercontent.com/3986214/107527709-5ee32b80-6bb9-11eb-883c-575a4b2a4ce7.png)

**Comment by Turbo87** [comment]
@steffahn FYI this is only going to be a temporary state. My long-term goal is to make it a tab at the top of the page, roughly similar to what the npm registry is doing (e.g. https://www.npmjs.com/package/react). For that to happen we needed to move it out of the quick links for now though.

**Comment by Turbo87** [comment]
but you're right that this issue can probably be closed now because this is currently implemented now
