### ISSUE TITLE
Crate should be marked as "does not build" when dependency has all its versions yanked

### ISSUE THREAD

**Issue by MaciekTalaska** [rust-lang/crates.io#2083]
I think it could be a good idea to show that a particular crate can not be build if one of the dependencies has all of its versions yanked. 

In such a case it is impossible to use the crate without making changes to the source of the crate itself, and (what is very important for some people) it is not possible to use `cargo install` (as the crate will not be build).

For an example, please have a look at the following crate: https://crates.io/crates/lobsters

**Comment by smarnach** [comment]
Yanked dependencies should not affect your ability to build a crate. Yanked versions can still be downloaded, so dependent crates should continue to build.

The example you gave can't be installed with `cargo install` because it does not contain any binaries. The binary for this lib is in the `lobsters-cli` crate, which the author did not upload to crates.io. I suggest asking the author to upload that crate, which will allow you to run `cargo install lobsters-cli`.

I will close this issue for now. Feel free to reopen it in case I misunderstood the issue.

**Comment by carols10cents** [comment]
Aside from the issue of `lobsters` not including any binaries, there *is* an issue with `cargo install` ignoring the lockfiles that may exist with a binary crate. Rust 1.37 added a `--locked` flag you can pass to `cargo install` to tell it to use the lockfile, which should allow the crate to depend on any yanked versions that appear in said lockfile. Related: https://github.com/rust-lang/cargo/issues/7169#issuecomment-514361495
