### ISSUE TITLE
background-color not set when color is set

### ISSUE THREAD

**Issue by mrmonday** [rust-lang/crates.io#241]
If the `color` property is set in CSS, the `background-color` property should also always be set, and vice versa. This is not currently true for crates.io, leading to situations like this:

![2015-12-19-011737_501x102_scrot](https://cloud.githubusercontent.com/assets/165689/11910436/52dc740e-a5ee-11e5-8ce6-1e9453238730.png)

Where the text is unreadable due to custom styles. See also, note 4 here: http://www.w3.org/TR/WCAG20/#contrast-ratiodef. There's probably a better/more direct link, I couldn't find it though, unfortunately.

**Comment by esclear** [comment]
This issue is probably resolved already.

In [app.scss:136](https://github.com/rust-lang/crates.io/blob/master/app/styles/app.scss#L136) a background color for the search is set.

Considering that the background pattern shall remain in the header, there is no background set for the header, just `none` for its children (the buttons).

And since a [background-color is set for the `#main`-`div`](https://github.com/rust-lang/crates.io/blob/master/app/styles/app.scss#L48) that is inherited by all its children, it seems that all such cases are already accounted of.

**Comment by carols10cents** [comment]
@esclear thank you for investigating this! Checking that it's indeed fixed is a huge help :) Closing!
