### ISSUE TITLE
clicking a search result removes the results page from history

### ISSUE THREAD

**Issue by durka** [rust-lang/crates.io#252]
Steps to reproduce:

1. Go to https://crates.io/
2. Search for "foo" and click on the first link ("tenacious").
3. Search for "bar" and click on the first link ("bar").
4. Click the back button. You end up back at the tenacious page, skipping the search results page.

Possibly related to #236 or its fix.

**Comment by jdm** [comment]
This is a surprisingly annoying papercut!

**Comment by huonw** [comment]
This seems to affect the front-page too (got to https://crates.io, click on a crate, and then going back will skip the first page).

**Comment by Keats** [comment]
It's probably the same bug:

- I go to Crate A page
- I click on one of the dependency
- I hit back and go back to a page before the crate A

The issue is probably due to the use of replaceWith like https://github.com/rust-lang/crates.io/blob/master/app/routes/crate/index.js#L5. I don't know ember but couldn't the trailing slash issue not be handled in the code itself but done instead in nginx or whatever the server is using? Replacing urls in the history is rarely wanted

**Comment by durka** [comment]
Confirmed that this was indeed caused by #251. Working on a fix.
