### ISSUE TITLE
Add icons for documentation, repo, dependant crates link, etc..

### ISSUE THREAD

**Issue by codec-abc** [rust-lang/crates.io#2520]
Hi,

Catching myself looking for the documentation and Github link for a crate, I realized I often struggle to find these links (usually searching on the right column before realizing they are not here). This is probably because I don’t do enough Rust bust still I think adding some icons to the links for a crate under its name would improve readability because icons are more easily catch by the eye in a glimpse than text:

So instead of something like:
![image](https://user-images.githubusercontent.com/1208646/82453848-58ec6e00-9ab1-11ea-834f-0ceb1b836134.png)

We would have something like:
![image](https://user-images.githubusercontent.com/1208646/82454699-5dfded00-9ab2-11ea-9558-7ff04ae0e2ef.png)

What do you think?

**Comment by pichfl** [comment]
@Turbo87 summoned me here.

The problem here is not the missing icons, but the lack of visual and calculated contrast of these links. 

#00ac5b on #edebdd [does not provide any reasonable contrast](https://webaim.org/resources/contrastchecker/?fcolor=00AC5B&bcolor=EDEBDD), which makes it very hard to spot them. Reducing the font-size to 80% of the default doesn't help either.

I'm not against introducing icons, I just want to make sure they match the overall theme if we introduce new ones. 

In the mean time, removing the font-size: 80% and maybe even replacing the darker header background with white will improve contrast a lot and therefore also visibility. Moving the links down by 1rem (reducing the bottom spacing of the header by the same amount will also help to eliminate the problem without introducing new elements.

**Comment by codec-abc** [comment]
I agree that contrast and font size is not optimal right now. And I also understand that you don't want to introduce icons. Yet, I have the feeling that icons would help visualy parse the page.

Maybe this can be done in 2 steps where the first one is dealing with the low hanging fruit (fixing font size, contrast) and once done we can see about icons.
