### ISSUE TITLE
HTTP 404 when using double slash in URL

### ISSUE THREAD

**Issue by pravic** [rust-lang/crates.io#2552]
`https://crates.io//api/v1/crates/bat` HTTP 404
`https://crates.io/api/v1/crates/bat` HTTP 200

**Comment by Turbo87** [comment]
this looks like intended behavior to me. why do you think that double slash should be supported?

**Comment by pravic** [comment]
Why do you think that double shash shouldn't be supported?

I believe, most of servers handle it properly: https://stackoverflow.com/questions/20523318/is-a-url-with-in-the-path-section-valid

**Comment by Turbo87** [comment]
> Why do you think that double shash shouldn't be supported?

because it looks like a different path to me, and I don't see why anyone using the API would not just use the correct path directly

**Comment by jtgeibel** [comment]
I've opened PR #2615 to address this. I'm adding this because of backwards compatibility, since our previous server supported these types of URLs. In general I think this is only necessary when serving arbitrary files from the file system, to ensure directory traversal doesn't provide access to files outside of the server root (such as to `/etc/passwd`). For example, the nginx proxy we have in place isn't normalizing the path sent to the backend (although it does by default when serving files directly, such as files in `/assets/`).
