### ISSUE TITLE
Allow API tokens to self-revoke

### ISSUE THREAD

**Issue by jsha** [rust-lang/crates.io#2653]
Right now, API tokens have sufficient authorization to revoke themselves via:

```
curl -X DELETE https://crates.io/api/v1/me/tokens/:id -H 'Authorization: cioAbCdEfGhiJKLmnop'
```

This is particularly useful if, for instance, someone is managing an API token that doesn't belong to their personal account, and needs to revoke it after accidentally disclosing it. It's also useful because if a third-party researcher finds that a token is disclosed, e.g. in CI logs, they can immediately revoke it without waiting for the token owner to respond (if they can find the token owner).

However, this method requires that the revoked know the token ID. It would be good to offer a similar method to DELETE the current token without knowing its ID.

(Followup from https://github.com/rust-lang/rfcs/pull/2947#issuecomment-661943761)

**Comment by pietroalbini** [comment]
A possible endpoint could be `DELETE /api/v1/me/tokens/current`. I'll add this to the team agenda to see if this is something we want to implement.

**Comment by pietroalbini** [comment]
We [discussed this during the weekly crates.io team meeting](https://discordapp.com/channels/442252698964721669/448525639469891595/736229261110673520), and agreed we should have a similar endpoint! The URL should be:

```
DELETE /api/v1/tokens/current
```

The URL intentionally does not have a `/me`: the current API is technically unstable, and since this should be actually a stable and documented endpoint we'd prefer this URL schema. If anyone wants to implement it feel free to send a PR!
