### ISSUE TITLE
Crates.io doesn't work with classic Opera browser

### ISSUE THREAD

**Issue by pravic** [rust-lang/crates.io#290]
It looks like this: http://i.imgur.com/4cNpuNQ.png

Opera 12.18.

**Comment by pravic** [comment]
Also the "Docs" menu is not shown near "Browse All Crates" at http://doc.crates.io.

**Comment by tshepang** [comment]
does this still happen

**Comment by pravic** [comment]
[yep](https://gyazo.com/cec88fd6b5ca46520f90387bf8254016)

**Comment by rjgoldsborough** [comment]
Do you happen to be on a windows machine?

Opera 12 was the last version before the presto -> blink switch over, and it seems like they only released 12.18 for windows.

12.18 was released in Feb of this year but the last update to 12 before that was April 23, 2014, Opera 12.17 and it seems like they are only still maintaining presto for opera mini.

I'm guessing that the site is just using stuff that presto doesn't support? I'm not exactly sure what the list of features is at this point. It looks like the last stable release of it was 2013?

http://www.opera.com/docs/specs/presto2.12/

I downloaded the 12.16 version for osx because I don't have a windows vm handy and it didn't look quite as bad as your bug but the doc dropdown is busted.
![screen shot 2016-08-29 at 1 37 22 pm](https://cloud.githubusercontent.com/assets/868959/18069125/dac3630e-6df9-11e6-97a0-77383784683a.png)
![screen shot 2016-08-29 at 3 08 04 pm](https://cloud.githubusercontent.com/assets/868959/18069235/82a81f24-6dfa-11e6-8105-b9ea874c0768.png)

I am also getting *A LOT* of errors in 12.16.

Could you take a screenshot of the errors you are getting?

**Comment by carols10cents** [comment]
Per [RFC 1985](https://github.com/rust-lang/rfcs/blob/master/text/1985-tiered-browser-support.md), Opera is not one of the supported browsers. We'll accept pull requests to fix any of these issues, but we've chosen to spend time elsewhere rather than on supporting every version of every browser. Thanks!
