### ISSUE TITLE
Web UI for removing an owner doesn't display errors; looks like it works when it doesn't

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/crates.io#2976]
In https://github.com/georust/geos/issues/80, the idea was to remove the owner "github:georust:core". I tried it with the command line:

```bash
$ cargo owner --remove 'github:georust:core'
    Updating crates.io index
       Owner removing ["github:georust:core"] from crate geos
error: failed to remove owners from crate geos

Caused by:
  api errors (status 200 OK): could not find the github team georust/core
```

And on the web interface at https://crates.io/crates/geos/owners. It's important to be noted that even though the web UI tells me it got removed, it wasn't. We can see it when reloading the page. So I guess it's another UI bug from the web interface too.

**Comment by carols10cents** [comment]
Looks like the removal failure is https://github.com/rust-lang/crates.io/issues/1818, so I'll leave this open for the UI failing to display the error and looking like it works instead.

**Comment by michaelkirk** [comment]
Just to clarify, @carols10cents updated the title to be about not displaying errors in the Web UI, but I'm not yet sure that's the entirety of the issue.

Perhaps that's also a problem, but ultimately the issue here was that we weren't able to remove the team from the crate owners. Maybe showing a proper error message will elucidate *why* we aren't able to remove the team, but that's not clear to me.

In particular, the linked issue doesn't seem to apply: https://github.com/rust-lang/crates.io/issues/1818 is about the inability to remove an owner if that team has been deleted on GH. But that's not the case here - the github:georust:core team still exists on GH.

**Comment by GuillaumeGomez** [comment]
Yes, there are two errors:
1. the error isn't reported correctly on the UI
2. we can't remove an owner if it's a team

**Comment by Turbo87** [comment]
I've just done a quick investigation on this and I've found two issues:

- pages like https://crates.io/crates/serde/owners are currently accessible by anyone, even if they are not an owner themselves (somewhat unrelated to the issue here though)

- when clicking on a "Remove" button on that page the API response is `{"errors":[{"detail":"only owners have permission to modify owners"}]}`, but it is returned with a `200` (OK) status code. According to the backend code "this is for backwards compatibility with cargo endpoints", but our frontend code assumed that it would get an error status code.

I'll get a PR ready to resolve that frontend issue. Sorry for the trouble here. :-/
