### ISSUE TITLE
Pressing back too fast break navigation

### ISSUE THREAD

**Issue by nox** [rust-lang/crates.io#3041]
When browsing search results, pressing back too fast sometimes break navigation.

**To Reproduce**
1. Go to crates.io
2. Search for "foo"
3. Click on "2"
4. Click on "3"
5. Press twice on the browser's back button quickly

**Expected behavior**
The first page of results should be shown, but crates.io keep showing the second.

**Screenshots**
<img width="1847" alt="Capture d’écran 2020-11-24 à 14 30 44" src="https://user-images.githubusercontent.com/123095/100100879-c4990480-2e61-11eb-88eb-eef11a25ed10.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox 85 (nightly)

**Additional context**

**Comment by Turbo87** [comment]
I don't think there is much we can do about this, and I've had things like this happen on plenty of other pages too. It looks like while the browser is still busy loading the content of the previous page it sometimes does not accept the next "previous page" button clicks.

Unless anyone has a suggestion on how to fix this, I would propose to close this issue since this seems out-of-scope for us to fix in a reasonable way.

**Comment by nox** [comment]
Closing the issue doesn't make the problem disappear, I don't see the point of closing this even if there is no fix delivered in a short time.

**Comment by Turbo87** [comment]
I personally don't like to keep issues open that are not actionable in a reasonable way. As I said, if someone can come up with a good way to fix it then let's do it, but I currently don't see one. and tbh it doesn't seem like a huge issue to me either.

**Comment by shadowcat-mst** [comment]
"Find whatever javascript batshittery is breaking it and turn it of" seems perfectly actionable.

**Comment by Turbo87** [comment]
@shadowcat-mst that is not a constructive comment at all. I would recommend that you have a look at https://www.rust-lang.org/policies/code-of-conduct before posting comment with such strong language. we're all doing this in our free time here and and being so aggressive is helping nobody.

**Comment by shadowcat-mst** [comment]
There is, for example, an entire Ember London talk from 2018 called "Back Button Hell" because handling this sort of stuff in javascript is just full of sharp edges as a matter of course, and frankly the working solutions are usually made entirely out of batshittery let alone the non-working ones.

Your unwelcoming and dismissive attitude to a valid bug report with an actionable solution around basic web navigation with accessibility implications is unnecessary and I'd suggest this bug should be re-opened so somebody a bit more familiar with the ember navigation stuff can look into it.

**Comment by shadowcat-mst** [comment]
(annoyingly, I can't repro this in my local firefox install, so my grand plan to break out the debugger and see if I can spot anything is apparently not going to come to fruition without assistance from somebody else)
