### ISSUE TITLE
Allow non-http `repository` urls

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/crates.io#3139]
**Is your feature request related to a problem? Please describe.**
I attempted to publish a project that has its repository hosted on a non-http based hosting platform and crates.io rejected the upload.

```
error: api errors (status 200 OK): URL for field `repository` must begin with http:// or https:// (url: rad:git:hwd1yre85oenojqfpzt1ihd36enmupg4dnb1o78rsos8h957bpxxbzn5g4a)
```

**Describe the solution you'd like**
Allow any valid [absolute](https://github.com/rust-lang/crates.io/issues/169) url for the `repository` field.

**Comment by Turbo87** [comment]
I would assume that this kind of thing will need an RFC since it probably has downstream effects on other tooling that assumes HTTP links here.

**Comment by Nemo157** [comment]
Was that ever a guarantee? https://doc.rust-lang.org/nightly/cargo/reference/manifest.html#the-repository-field just says URL and cargo accepts a non-https url just fine.

**Comment by Turbo87** [comment]
questiong is: what is considered a URL? 😅

**Comment by carols10cents** [comment]
I think the reason we added this is because people were just specifying
`githubacct/reponame` and expecting us to infer GitHub, so we wanted to
make it clear that crates.io expects a full URL.

What does the URL that you want to specify look like? Does it start with
git:// perhaps?

**Comment by jtgeibel** [comment]
I think we could consider allowing `git:`, `svn:` and a few other SCM schemes, but we would want to want to filter them out in the frontend because these aren't useful links that a browser can navigate to. Given that, I'm not sure that allowing `git:` and similar schemes is all that useful.

Also, as far as I can tell, cargo does no checking of this field at all. It doesn't complain when setting `repository = "not a URL"`. Verification of some of these fields has always been server side only.

In this case in particular, beyond references to RAD Studio, I can't find any details on the `rad:git:` scheme.

**Comment by Nemo157** [comment]
The url is `rad:git:hwd1yre85oenojqfpzt1ihd36enmupg4dnb1o78rsos8h957bpxxbzn5g4a` which is related to https://radicle.xyz/, a p2p project hosting platform. They don't currently, but at some point in the future I expect the desktop app to have a registered scheme handler so that clicking the link would actually work.

**Comment by Turbo87** [comment]
Hi @Nemo157. We just discussed this issue in our weekly team meeting and concluded that we prefer to only support mainstream URLs for now (http, https, ...), that users can directly open in their browsers.

A potential workaround for you would be to use a redirection service that supplies you with an https link and that redirects to the radicle URL.
