### ISSUE TITLE
Searching for "which" does not show the "which" crate

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/crates.io#321]
https://crates.io/search?q=which

Crates that should have shown:
- https://crates.io/crates/which
- https://crates.io/crates/quale

**Comment by lazypenguin** [comment]
Looks like this is an issue with the postgres query. The `which` lexeme in the tsquery is considered a "stopword" by postgres's text search facilities: https://www.postgresql.org/docs/9.3/static/textsearch-dictionaries.html#TEXTSEARCH-STOPWORDS

Not sure what kind of flexibility there is with postgres on heroku but it seems the best action would be to alter the default text dictionary configuration to use a new stop list.

Default stop list (English) on debian `/usr/share/postgresql/9.5/tsearch_data/english.stop`

Seems that either:

1.  `english.stop` can be modified on the server to remove stop words, or
2. Could potentially alter the default `simple` dictionary configuration to use a new stop list all-together: `https://www.postgresql.org/docs/9.3/static/sql-altertsconfig.html`

**Comment by casey** [comment]
Just ran into this with the `just` crate: https://crates.io/crates/just

**Comment by casey** [comment]
How is the database configured and hosted? I wasn't able to find any postgres specific configuration in this repo.

**Comment by rminderhoud** [comment]
I believe crates.io is hosted on Heroku which pushes for configuration settings to be pulled in from environment variables. This is the line you're looking for:

https://github.com/rust-lang/crates.io/blob/master/src/bin/server.rs#L104

It seems Heroku is not very robust in allowing us to edit the configuration files of postgres so the solution to this problem would be to create a new stoplist (`crates.io.stop`?) and then alter the database to use our new configuration with our new stoplist.

**Comment by carols10cents** [comment]
Correct! The database is hosted on Heroku.

**Comment by casey** [comment]
Okay, I dug into this a little bit and got things configured locally so that searching with stop words works.

Searching is a two step process, the query text is first turned into a `tsquery`, which is then used to search a `tsvector`. So, in order to make searching with stop words work, they need to be retained in both the `tsquery` and in the `tsvector`.

Search queries are turned into a `tsquery` with the `plainto_tsquery()` function [here](https://github.com/rust-lang/crates.io/blob/71791bea75773a9142a28778edd0f92a2e076faa/src/krate.rs#L683).

By setting `default_text_search_config = 'simple'` in the configuration file, the `tsquery` thus obtained will contain stop words. One can also do it via SQL as `set default_text_search_config to 'pg_catalog.simple';`.

By changing `pg_catalog.english` to `pg_catalog.simple` in `migrations/20160219125609_dumped_migration_105/up.sql` stop words will also be retrained in the `tsvector`.

Both of the above changes result in searches for stop words working.

So, a few questions:

1. Is allowing searches with stop words what we actually want? I think so! But then again, I'm the author of a crate whose name is a stop word, so I might biased.

2. What's the right way to retain stop words in the `tsquery`? There are three options:
  a. Change `default_text_search_config` via configuration
  b. Change `default_text_search_config` via SQL in a migration
  c. Change it via teaching diesel-rs/diesel_full_text_search the two-argument form of `plainto_tsquery()` which takes as its first parameter a config, and passing in the 'simple' config? (Postgresql supports this, but diesel_full_text_search doesn't expose it.)
  (I think c is probably the best way, since it makes it explicit, and doesn't rely on an ambient configuration setting.)

3. After `textsearchable_index_col` is changed to use `pg_catalog.simple`, will we need to rebuild it?

**Comment by sgrif** [comment]
I don't think switching to using `simple` is the right call here. We're searching on a lot more than just the title, and we lose much of the functionality that way. I agree that searching for `which` should return the crate titled `which`, but excluding the crate `quale` is not a bug. `which` is a stop word for a reason. The solution here is likely just to add a `.or(crates::name.eq(q_string))` to the filter.

**Comment by casey** [comment]
@sgrif That seems reasonable, I think that's a better fix.
