### ISSUE TITLE
Keywords are not shown via search box

### ISSUE THREAD

**Issue by troplin** [rust-lang/crates.io#331]
When using the search box to find a crate and the using the link from the search results to navigate to that crates's page, keywords are not shown until the page is reloaded

This is yet another strange dependency on the referrer page, like issue #306.

**Comment by rjgoldsborough** [comment]
I found the ember debugger and noticed something funky going on I believe.

The first screenshot below is the first page load after clicking hyper from the search page.
The second is after a page reload.

As you can see, the first time ember seems to be loading the same 10 models from the search page (weird caching?). But the second time it only retrieves the one.

I'm fairly new to ember so I'm not sure why that would happen but it seems like something that could cause issues.

This line I think specifically `keywords: computed.alias('crate.keywords')`.
Since there are 10 crate models vs the 1?

![screen shot 2016-08-30 at 5 08 32 pm](https://cloud.githubusercontent.com/assets/868959/18111457/9b0390f0-6ed4-11e6-9ddc-bf1849e13b49.png)
![screen shot 2016-08-30 at 5 09 06 pm](https://cloud.githubusercontent.com/assets/868959/18111458/9b187380-6ed4-11e6-8bd5-484d02c969f9.png)

**Comment by carols10cents** [comment]
I'm seeing this happen with the new category functionality that I'm adding as well, categories also fail to show up on a crate's page if you navigate to that page from a list of crates. They do show up if you visit the URL of a crate's page directly or if you reload the crate page after arriving :(
