### ISSUE TITLE
Improve prominence of "dependent crates" link

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/crates.io#3321]
Like https://github.com/rust-lang/crates.io/issues/2075#issuecomment-776820104, I was disappointed by the relocation of the "dependent crates" a.k.a "reverse dependencies" link in #3226 from the page header to just about the least prominent item on the page.

Anecdotally this link is the second most important thing I ever come to crates.io for, after the "repository" link. Aside from the readme, it's maybe the most important piece of information crates.io exposes for evaluating the suitability of a crate. https://github.com/rust-lang/crates.io/issues/2075#issuecomment-776820104 covers a bunch more reasons why the current UI is problematic.

In https://github.com/rust-lang/crates.io/issues/2075#issuecomment-776850857 it was mentioned that the reverse dependencies information is planned to be relocated to a tab near the top. I am opening this issue for a way to prioritize and track any discussion on that work.

<br>

## Before:

<img src="https://user-images.githubusercontent.com/1940490/108800231-6f938a00-7547-11eb-9539-b46e34fab38e.png" width="700">

<br>

## After:

<img src="https://user-images.githubusercontent.com/1940490/108800237-715d4d80-7547-11eb-8323-55478b564bcb.png" width="500">

**Comment by Turbo87** [comment]
you are right, it should be moved back to a more prominent place. I already have plans on doing that, but they are delayed a bit at the moment because people are busy and it takes a while to get reviews. (and just to be clear, I'm not blaming anybody for that)

the reason why it was moved is that we want to adjust the header a little bit, and for that we first had to move out a few things because we didn't want to remove them completely.
