### ISSUE TITLE
Is crate.io a good choice for internal network private crate  registry?

### ISSUE THREAD

**Issue by wangkirin** [rust-lang/crates.io#3361]
Hi guys:
I'm trying to deploy a private registry in the enterprise internal network(can't connect to internet directly). And I found there are only few projects are designed to do this (such as [alexandrie](https://github.com/Hirevo/alexandrie)).

And I found that crate.io can deploy as local mode  [https://github.com/rust-lang/crates.io/blob/master/docs/CONTRIBUTING.md#setting-up-a-development-environment](https://github.com/rust-lang/crates.io/blob/master/docs/CONTRIBUTING.md#setting-up-a-development-environment),  I want to consult is `crate.io` a good choice for internal network private crate  registry in production?  thank you

**Comment by plaets** [comment]
It still requires you to login with github in local mode, if you have no internet connection at all it's not a good choice.

**Comment by wangkirin** [comment]
> It still requires you to login with github in local mode, if you have no internet connection at all it's not a good choice.

Yes,  that means we need to adjust the authentication system, thank you for  reminding
Is there anything else we haven't noticed？

**Comment by Turbo87** [comment]
hello @wangkirin,

thanks for the question. we've discussed this topic in our team meeting today and came to the conclusion that the crates.io codebase is primarily meant to run the crates.io page itself.

this means:
- we do not officially support this use case of running it as a private registry
- we are unlikely to accept contributions to change that, due to the additional maintenance burden
- we are open to people experimenting with it, but they should be aware of the above two points

if you search the internet for "rust private registry" you can find a few projects that appear to have started building such things, but at this point we can't officially recommend any of these projects. not because they might be bad, but just because we don't have any experience with them either.
