### ISSUE TITLE
Please put docs and repo links back to the top of the page

### ISSUE THREAD

**Issue by ijackson** [rust-lang/crates.io#3377]
**Describe the bug**

The links to a project's documentation and repository are much harder to find quickly than they used to be.

**To Reproduce**

1. Go to https://crates.io
2. enter "serde" in the search box, and click through to `https://crates.io/crates/serde` to read the `README`
3. Decide to read the docs or visit the repo to look at issues/MRs/etc.
4. Try to find the docs link on the page.
5. Scan through the stuff in the right sidebar and eventually find it.

**Expected behavior**

The links to **documentation** and **repository** shoudl be as prominent as they were before the recent update, and as prominent as they are on the search results page.

They should be at least as prominent as the new keywords links.  They should be in a fixed location on the page, near the top (so they should not ever require scrolling or visual scanning of the page).

Ideally they would be restored to a location similar to their previous location, before the last redesign, so as to provide continuity for existing users.

IMO such a high prominence and consistency of location is necessary because these links are not simply metadata or information about the package.  They are key elements of the navigation structure between crates.io, docs.rs, repositories, and general search engines.

**Additional context**

I appreciate that filing this as a bug rather than a feature request or something might be seen as overly insistent.

However it seems to me that it would be difficult to argue that the documentation and repo links are less important than the last update, the crate source code size, or the "Install" fragment with c&p for Cargo.toml.  Rather, the fact that the docs and repo links are on the search page suggests that it is recognised that these are critically important navigation.  Having these two links then buried so badly on the next page is poor UI design.

On a personal and more subjective note I find this change major useability regression, and it seems there are others who agree.

I think calling this a bug is justified by the combination of (as I see it) a problem which (i) can to a large extent be characterised objectively (ii) is a significant regression (at least for a number of people) compared to previous behaviour.

I found #3352.  Some of the comments there provide additional context and motivation for my request.

I am filing this as a separate report because I thought it would be helpful to set out explicitly a report which contains only a request for llimited, specific,  and immediately actionable changes.

I'm hoping that we can keep #3352 for general discussion of the new layout and principles for managing the crates.io web UI, and keep this issue for specifically the location of the docs and repo links.

**Comment by Turbo87** [comment]
FWIW several people have also expressed that they very much like these changes, and there are quite a few other package registries that do similar things. in other words: I find it quite a strong statement to claim that this is objectively a major useability regression.

as you can see at this point, we haven't just moved the links, but we've also made it easier to see where those links link to, so that you don't have to click blindly or hover over the link to see where it goes. this simply wouldn't have been possible by keeping them horizontally next to each other in the header bar.

> The links to a project's documentation and repository are much harder to find quickly than they used to be.

I think this is primarily caused by those links being in their old positions for such a long time, and adjusting to UI changes can be hard if you've become used to seeing things in the same place all the time. I'm confident though that you are able rewire your brain to look for the links in their new positions.
