### ISSUE TITLE
`tempfile` crate not found when searching for "temp file"

### ISSUE THREAD

**Issue by mleonhard** [rust-lang/crates.io#3450]
**Describe the bug**
I searched for a [temp file](https://crates.io/search?q=temp%20file) crate on crates.io.  The [`tempfile`](https://crates.io/crates/tempfile) crate does not appear in the 10 pages of results.

**To Reproduce**
1. Go to 'https://crates.io/search?q=temp%20file
2. Search the result pages for "tempfile"

**Expected behavior**
The `tempfile` crate appears in the results.  Since it is so popular, I expect it to be the first result.

**Screenshots**
![Screen Shot 2021-03-21 at 19 00 03](https://user-images.githubusercontent.com/520739/111931131-c83b4180-8a77-11eb-91c0-ca928a4d7ab6.png)

**Desktop (please complete the following information):**
 - macOS Catalina 10.15.7
 - Safari 14.0.3

**Comment by mleonhard** [comment]
Searching for "temp dir" also doesn't show the `tempdir` crate:

https://crates.io/search?q=temp%20dir

**Comment by Turbo87** [comment]
This issue is roughly similar to https://github.com/rust-lang/crates.io/issues/2746 and https://github.com/rust-lang/crates.io/issues/1270. I'm closing this as a duplicate, but thanks for reporting. I agree that the search could be better, but with our current infrastructure it appears to be hard to achieve.
