### ISSUE TITLE
Ops: Prepare for postgres upgrade

### ISSUE THREAD

**Issue by jtgeibel** [rust-lang/crates.io#3480]
I see no urgency for this migration, but we should start planning for an eventual upgrade. We are currently on PG11 and PG13 is available on Heroku for production use.

Heroku's [`pg:upgrade`](https://devcenter.heroku.com/articles/upgrading-heroku-postgres-databases#upgrading-with-pg-upgrade) serves as a guide. We will want to document our own detailed steps and test them out on staging. In particular, we may want to temporarily setup a real leader/follower configuration on staging. (Currently, both connection pools point to the same database on staging.)

We will also need to make sure the new download tracking logic works well in read-only mode (dropping download counts for the duration of the migration).

To minimize the time we operate in read-only mode, we will probably want to land #3479 first.

**Comment by Turbo87** [comment]
https://github.com/rust-lang/crates.io/pull/3886#issuecomment-913432943 might be a good reason to do this in the near-term future

**Comment by Turbo87** [comment]
we discussed this topic in our weekly team meeting today:

- it would be good to resolve https://github.com/rust-lang/crates.io/issues/3479 before the upgrade, but it is not strictly required. resolving it after the upgrade means that the upgrade might take a little bit longer since more data needs to be migrated.
- it should be possible to create a temporary follower database and upgrade that to get a feel for how long the migration would take, and thus the amount of time we would have to spend in read-only mode.
- @pietroalbini will look into this on the weekend and write down some instructions
- the actual upgrade should happen during a Zoom call with @jtgeibel @pietroalbini and @Turbo87 to immediately address any issues that come up

**Comment by pietroalbini** [comment]
So, I created a throwaway follower and performed the upgrade on it, and it took between 7 and 8 minutes for the upgrade to finish. This would allow us to have a 10 minute read-only window, which is not bad.

The main worry I have is about the read-only follower used for the more heavy queries: when the database is upgraded the old followers are detached, so they can't be used with the new primary. This would mean we'd need to first upgrade the primary from PostgreSQL 11 to PostgreSQL 13, and *then* create a new read-only follower.

Unfortunately followers can't be created straight away from the upgraded database, as the capability to create a follower database is marked as "temporarily unavailable". According to the [Heroku documentation](https://help.heroku.com/15G855IX/how-long-does-it-take-for-a-new-database-to-get-fork-follow-and-rollback-capabilities) a backup is required before being able to create the follower, and backups are hard-capped at 10MB/s. With the current database size (8.2 GB) this would mean waiting at least 13 minutes before we can start creating the new follower, leaving a window when all the queries must go to the primary database. 13 minutes is not *that* bad though.

**Comment by pietroalbini** [comment]
> it would be good to resolve #3479 before the upgrade, but it is not strictly required. resolving it after the upgrade means that the upgrade might take a little bit longer since more data needs to be migrated.

An advantage of resolving #3479 before the upgrade would be actually shrinking our database: the `version_downloads` table currently takes more than 6 GB, but even if we delete the data we can't do a `VACUUM FULL` in production, otherwise we'd break the website until it finishes. Running the upgrade with `pg:copy` instead of `pg:upgrade` would allow us to compact the table and perform the upgrade at the same time without breaking the website.

**Comment by Turbo87** [comment]
given that we've updated to Postgres 13 a while ago, I guess we can close this issue.
