### ISSUE TITLE
An error occurred: Oops, that route doesn't exist!

### ISSUE THREAD

**Issue by QiangHeisenberg** [rust-lang/crates.io#3579]
I built my own private crates.io and now there's a problem. I entered various routes into the browser, but all of them showed up to be nonexistent. I don't know what the problem is, is this a bug in crates.io building private crates.io?

The ```cargo run --bin background-worker``` command has been run.

I type ```https://crates.io/api/v1/crates/rand/0.8.3/download``` in my browser and download rand crates. But I type in ```http://crates.xxxxxx.com/api/v1/crates/ok/3.5.0/download``` and it returns ```Oops, that route doesn't exist!```.

As a supplement to the problem, I'm not sure what the problem is and why all of my routes are non-existent.
Includes:
```
http://crates.xxxxxx.com/api/v1/me
http://crates.xxxxxx.com/api/v1/download
http://crates.xxxxxx.com/api/v1/crates/test-li
http://crates.xxxxxx.com/api/v1/crates/test-li/0.1.0/authors
......
```

where ```ok``` and ```test_li``` are my own test crate.

**Comment by jtgeibel** [comment]
Hi @QiangHeisenberg, this codebase is developed for the specific needs of the official crates.io website. A lot of this code was written before cargo supported alternative registries and since then usage in external deployments has not been a goal for this project. Unfortunately we are not able to provide support for use as 3rd party alternative registry.
