### ISSUE TITLE
Download charts are inaccurate (especially for "other")

### ISSUE THREAD

**Issue by PythonCreator27** [rust-lang/crates.io#3631]
**Describe the bug**
The download graphs are inaccurate for the "other" amount and other versions too.

**To Reproduce**
1. Go to https://crates.io/crates/ring
1. Scroll down to the downloads graph
1. Hover over March 8
1. See that the graph and the popup shown are different for the "other" amount (24,000 should not be over the 25,000 line).

**Expected behavior**
24,000 should be under the 25,000 line, not over it.

**Screenshots**
![image](https://user-images.githubusercontent.com/67528879/117393213-441f0b00-aeb9-11eb-902f-f729da65343a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 89.0b8

**Additional context**
This happens for almost *any* day and *any* crate. Try actix, or smallvec, or serde. Some are wildly inaccurate (2,500 over a 3,000 mark). Also happens in Chromium Edge.

**Comment by Turbo87** [comment]
What you are seeing on that page is a stacked chart, which means that the topmost line in the chart is the total number of downloads. You can click on the colors in the legend to disable the other lines if you want to know the downloads for just a single version.

**Comment by carols10cents** [comment]
Can confirm the behavior @Turbo87 described that the graph is stacked as expected, and turning off all except "other" makes the "other" dot for March 8 appear beneath 25,000:

<img width="1045" alt="Screen Shot demonstrating expected behavior" src="https://user-images.githubusercontent.com/193874/118901855-4aae7900-b8e2-11eb-8f13-67da939fd559.png">
