### ISSUE TITLE
Redirect immediately when there's only one match

### ISSUE THREAD

**Issue by r00ster91** [rust-lang/crates.io#3651]
**Is your feature request related to a problem? Please describe.**
When I look for instance for the crate `yayagram` then I land on https://crates.io/search?q=yayagram and then I manually have to click on the first and only result to get to where I want to be.

**Describe the solution you'd like**
It would be time saving and much more efficient if crates.io automatically went directly to the crate's page when there is only one result.

**Describe alternatives you've considered**
Maybe only redirect exact matches.

**Comment by Turbo87** [comment]
hi @r00ster91. we've discussed this proposal in the team call last friday and we are a bit worried about the potentially confusing behavior, because for most users it's not predictable whether something only has a single result. in most of our searches we always ended up with multiple results, and since it would only save a single click we don't see this tradeoff as being worth it at the moment. thanks anyways for the suggestion :)
