### ISSUE TITLE
Provide some push-notification/webhook service for crate upload notifications

### ISSUE THREAD

**Issue by nagisa** [rust-lang/crates.io#381]
With projects like crates.fyi coming out it is becoming a desirable service to have a capability to receive some notification about new crate uploads. It could be either implemented as traditional webhook service or a long lived TCP connection-style-subscription thing.

**Comment by alexcrichton** [comment]
Yeah I think we definitely want the ability to register webhooks here, but for a fully-featured workflow we'd also need an automated way of registering webhooks (e.g. an API to register webhooks), and that may be somewhat tricky...

**Comment by lfairy** [comment]
This would be useful for cargobot (the crates.io announcer on #rust-bots) as well.

**Comment by benaryorg** [comment]
I proposed the #439 issue regarding VersionEye integration. I myself have never used VersionEye, but I think it at least partially offers the functionality that is under discussion here so one might think of implementing that first and see if people really have more demanding requirements.

**Comment by SimonSapin** [comment]
I’ve heard of some unrelated projects (ab)using Twitter to get broadcast notifications of various kinds of events. GitHub’s integration with Twitter could be enabled for https://github.com/rust-lang/crates.io-index so that a tweet is sent for every push or ever commit. Then services like crates.fyi / docs.rs can use Twitter’s streaming APIs to get notified.

This has downsides (such as being tied to a another closed platform owned by a for-profit company), but it would allow getting something running without building new infrastructure.

**Comment by Turbo87** [comment]
FWIW we have RSS feeds for crates.io now (see https://blog.rust-lang.org/2024/07/29/crates-io-development-update.html#rss-feeds), which serve a roughly similar purpose, but are a lot easier to support on our side. While these RSS feeds are pull-based, they do include all data from a certain timeframe, so if polls happen within that timeframe nothing should be missed. Building and maintaining a push-based system is currently not on our roadmap and I don't expect that to change for the foreseeable future.
