### ISSUE TITLE
Enforce semver rules

### ISSUE THREAD

**Issue by NeoLegends** [rust-lang/crates.io#435]
Elm does this. Whenever somebody pushes code to their package management system, it checks the public API for incompatibilities and checks whether those are reflected in the associated version number. This would be great for crates.io! See http://elm-lang.org/.

(Moved from https://github.com/rust-lang/cargo/issues/3074)

**Comment by bluss** [comment]
Different crates will have different standards for what a breaking change is.

**Comment by NeoLegends** [comment]
Could you elaborate that? I'm not really sure what you mean.

If my crate's public API changes and becomes incompatible, I can't see how there could be a different "opinion" on that?

**Comment by bluss** [comment]
Some inspiration from the API evolution RFC https://github.com/rust-lang/rfcs/blob/master/text/1105-api-evolution.md  This is just for Rust, but it forms a role model as well.

Some *breaking changes* are just minor changes according to that policy:

- [modules: New public items ](https://github.com/rust-lang/rfcs/blob/master/text/1105-api-evolution.md#minor-change-adding-new-public-items) (example: Which crate doesn't do this?)
- [Traits: Minor change: adding a defaulted item](https://github.com/rust-lang/rfcs/blob/master/text/1105-api-evolution.md#minor-change-adding-a-defaulted-item)  ([example 1 from num](https://github.com/rust-num/num/pull/212), [example 2 from itertools](https://github.com/bluss/rust-itertools/pull/115))

Other common issues:

- Changes that make type inference fail in some cases where it would previously not. Sometimes crate authors have to make a judgment of the severity.
- Bumping the required Rust version (some crates like to do this without a breaking change, others not) [discussion](https://users.rust-lang.org/t/rust-version-support-in-library-crates-best-practices/4405), ["updating the rust version is not a breaking change"](https://github.com/rust-lang/rfcs/pull/1619#issuecomment-240242943)
- Breaking changes in stable Rust that forces the hand of the maintainer into creating one of the other issues listed here. If say Rust 1.27 breaks your crate, do you abandon your crate's major version, or do you fix it? Either choice leaves your users with a problem (if the fix requires a major version bump, users must reconfigure crates. Version disparities may then cascade to reverse dependencies, hurts composability of crates until everyone is on the same version of an integration crate again [like serde, num-traits, etc]).
  - There are some unfortunate but unavoidable breaking changes: type parameter defaults was syntax removed, for example
  - And avoidable breaking changes: for example Adding trait methods, [read_exact issue](https://internals.rust-lang.org/t/breaking-changes-by-adding-default-method-e-g-read-exact/2586)

Example from the messy real world:

- Behavioural changes can't be tested from the API and some are breaking and others are not (changing the output of Debug?).
- Some public traits are public to use and import, but not intended to be implemented
  - [ndarray::Dimension](https://bluss.github.io/rust-ndarray/master/ndarray/trait.Dimension.html)'s documentation is clear that this trait may change at will. It must be public so that it can be used as a trait bound, not because it's an interface that you'd implement.
  - Comment: Traits in Rust fill different roles, and not every public trait is an extension interface.

**Comment by tomaka** [comment]
> Changes that make type inference fail in some cases where it would previously not. Sometimes crate authors have to make a judgment of the severity.

As an example, I accidentally broke glutin by replacing `fn foo(_: String)` with `fn foo<T: Into<String>>(_: T)`, because some people were calling foo with `foo("hello".into())`.

**Comment by brson** [comment]
@badboy has done work on this: https://github.com/semantic-rs/semantic-rs

**Comment by badboy** [comment]
Yes, yes I have. Currently there's no actual code analysis in that crate, it solely relies on commit message conventions. My plan was and still is to have some code analysis to determine certain things. (I have some very very basic code somewhere which can at least detect function signature changes).

Putting all rules from RFC1105 into code will be incredibly hard. We won't ever get to a point where we don't miss a thing. And we definitely don't want to stop users from publishing versions, for which the server thinks they are breaking, but they are actually not.
I'm not sure enforcing semver from the server side is possible. After all semver is too vague for that.

**Comment by louy2** [comment]
It seems many prefer at least some level of check on server to nothing.

**Comment by withoutboats** [comment]
Identifying _every_ breaking change is impossible, since it seems easily reducible to the halting problem. But as a lint, this could be useful. For example:

* When a node of the public module/type graph has disappeared.
* When a type signature has changed. Preferably we'd distinguish between "more general" type parameters and hard breaks. Situations like @tomaka's can be resolved with a turbofish, but others are more serious breakages, and crates can set their own policies on what semver means to them.
* When adding an impl could be a breaking change. In theory this will be never, but there are certain exceptions (at least around auto traits).

In general, some tool which documents the changes to the public API of your library has many uses. Highlighting breakages/potential breakages is even better. I don't know if there are any breakages that crates.io should block upload on; I think its a potentially good idea but also potentially problematic.

**Comment by NeoLegends** [comment]
There is an RFC that states what is going to be a breaking change for the majority of cases. This would serve as the rules of the semver checker. 

If blocking a crate is not an option we could also issue a warning.

**Comment by cogman** [comment]
The main issues I see come up from specifically annotated/documented public APIs which are deprecated, unstable, or some other thing (beta? nightly? testing only?).

Unstable APIs in particular shouldn't force a major version bump.

I could see the argument for Deprecated methods requiring a major version bump.

**Comment by mickhrmweb** [comment]
> Unstable APIs in particular shouldn't force a major version bump.

What if the `unstable` annotation was handled differently or ignored?

**Comment by eternaleye** [comment]
@badboy:

> And we definitely don't want to stop users from publishing versions, for which the server thinks they are breaking, but they are actually not.

Could you expand on that? IMO, if a mechanical process _can_ detect a change that is breaking, then it _should_ block publishing. If someone removes a public type from their API, that _should_, in fact, force at-least-one of (major version bump, revert the change) as far as I can tell.

**Comment by NeoLegends** [comment]
There are some examples in the RFC that are technically breaking, but will compile fine in most cases. It wouldn't make much sense to prevent publishing a packet in that case.
However, in the cases the RFC states that something is a breaking change in all or most cases, the checker should definetely block.

The point is, the RFC explicitly defines those cases, so all of them can be detected and dealt with automatically.

**Comment by badboy** [comment]
> Could you expand on that? IMO, if a mechanical process can detect a change that is breaking, then it should block publishing without a major bump.

Bugs & false positives? I don't have a concrete example (and if I would we could easily fix that up front).
If this should be implemented it needs to be pretty conservative and catch only the minimum (removal of a public type should be easy to detect, other things not so much.

**Comment by bluss** [comment]
What about soundness fixes? [odds 0.2.17](https://crates.io/crates/odds) was published without a trait bound that was needed for a function to be memory safe. A few minutes later I realized the mistake in the new function and posted the bug fix as 0.2.18, which restricted the function by a trait bound. [fix commit](https://github.com/bluss/odds/commit/6ddfd87a5bff35793a6baa0d5c06a23beb8c4eb5)

**Comment by tomaka** [comment]
I think the best course of action is a plugin like clippy that would compare your current code with the old one and output warnings for breaking changes.
Then, it's the programmer's task to evaluate what's wrong.

**Comment by NeoLegends** [comment]
@cogman 
>Unstable APIs in particular shouldn't force a major version bump.

Unstable crates should use version numbers below `1.0.0`, for which the checker could / should be disabled.

The more I think about this, the better I like the idea of not hard-blocking crates from being published for the reasons posted above, integrating such a feature as linter into cargo makes the most sense to me. There will be cases that cannot be caught by a programmatic analysis (removing releases that contain sensitive data? Yanking?).

**Comment by setharnold** [comment]
> Unstable crates should use version numbers below 1.0.0, for which the checker could / should be disabled.

I'd suggest keeping it on before 1.0.0 as well: good habits learned during infancy of a project can carry over into good habits in adulthood.

Thanks

**Comment by jrmuizel** [comment]
FWIW, https://github.com/ibabushkin/rust-semverver is an implementation of a checker for this kind of thing.

**Comment by gerred** [comment]
> I'd suggest keeping it on before 1.0.0 as well: good habits learned during infancy of a project can carry over into good habits in adulthood.

I strongly disagree. There needs to be a period where a maintainer can signal that a project is in it's infancy and inherently unstable, and isn't forced into a contract before the project is ready to adopt it.

I see your point @setharnold about habits and agree. I also view this as unnecessarily constrictive given a <1.0.0 project is still in it's initial development phase considering: https://semver.org/#spec-item-4. A downstream user should be expecting to pin on exact versions before 1.0.0 since there isn't yet a contract, and I'd rather see cargo warning on anything but exact version pinning on crates that are <1.0.0.

**Comment by sgrif** [comment]
@carols10cents Would you agree that **if** this were to be considered, it would require a formal RFC? (and hence this issue should be closed)

**Comment by carols10cents** [comment]
Yes, I think hammering out the details of exactly how a tool like rust-semverver would be integrated into crates.io should have an RFC.
