### ISSUE TITLE
crates.io allows accidental publication of 2 identical versions of a crate seconds apart

### ISSUE THREAD

**Issue by Robinlovelace** [rust-lang/crates.io#4376]
### Current Behavior

2 identical releases of the same crate can be published on crates.io. It seems that there are no checks, other than the version number, to prevent accidental publication of multiple versions. See here for an example from just now: https://github.com/zonebuilders/zonebuilder-rust/commits/main

### Expected Behavior

It would be good to get an error or even a warning, e.g.

```
Warning: identical version (except for the version number) pushed within the last minute. Are you sure you want to continue?
```

If identical codebases are pushed in quick succession.

### Steps To Reproduce

1. Go into the root directory of a crate you maintain
2. Release a version
3. Change the version number
4. Release another version without any changes

### Environment

- Browser:
- OS:

**Comment by Turbo87** [comment]
On first glance I'd say this works as intended. Why would we prevent people from publishing similar code with different versions? With bugfix releases for older major/minor versions there might even be a legitimate use case for this.

From the technical side this is also not trivial. We could hash the crate file and compare the hashes of all previous versions of the crate, but, since the version number is part of the crate file, the hashes would all be different. In other words we would need to rewrite the crate file with a stripped version number, hash that, and then compare it, which is quite a bit of work for our server for relatively little benefit.

**Comment by Robinlovelace** [comment]
Could a hash be generated that excludes the version number?

**Comment by Turbo87** [comment]
only by extracting the full crate file upon upload, which we currently don't do for performance reasons.
