### ISSUE TITLE
lost crate ownership by renaming github username

### ISSUE THREAD

**Issue by dathinab** [rust-lang/crates.io#441]
Dear rust team,

Some time ago I published the `reep`/`reep-*` creates, through schedule changes I had not been able to continue this project. Today I wanted to do some cold maintenance updating the supported `iron` version to 0.4. But then noticed that I had no longer ownership of the crates. 

Looking into it it seems that `crates.io` still states the packages are owned by `naicode` which was my username on github until I changed it not long ago.

Given that I'm still listed as Author in the `Cargo.toml` file (with same email+real name) I hope this can be fixed.

**Comment by alexcrichton** [comment]
Thanks for the report! Your old `naicode` account on crates.io was effectively disabled due to https://users.rust-lang.org/t/security-advisory-for-crates-io-2016-08-15/6907, so there's no need to worry about anything! I've left that row disabled but transferred the crates to your new row, so you should be set and good to go!
