### ISSUE TITLE
crates.io index missing version that appears on crates.io

### ISSUE THREAD

**Issue by anowell** [rust-lang/crates.io#448]
https://crates.io/crates/rusty-machine shows 0.5.0 published 2 days ago, but [the index](https://github.com/rust-lang/crates.io-index/blob/master/ru/st/rusty-machine) shows 0.4.4 as the latest published version.

Sounds similar to #345

**Comment by alexcrichton** [comment]
Yeah unfortunately I've been able to track down what's going on here :(

For now I'd recommend a republish to at least fix the immediate problem.

**Comment by AtheMathmo** [comment]
I didn't realise this had already been posted - thanks @anowell !

I tried publishing 0.5.0 again and got an api error as the crate version already exists. Is my only option to yank and bump to 0.5.1?

**Comment by alexcrichton** [comment]
Yeah unfortunately you'll have to publish 0.5.1, sorry about that!

**Comment by AtheMathmo** [comment]
Have uploaded a new version which is downloading fine. It would be nice to know what caused this but feel free to close :)

**Comment by Byron** [comment]
Could this be related to having multiple concurrent writes to the index ?
Or it could be related to cargo being aborted in an inopportune moment, so that two calls that should have been atomic got ripped apart.

Assuming that one registry for the entire world would cause the multiple-writers issue to appear more often if is was actually present, maybe it is related to cargo being send sig-term during publish. I do remember to have done that when publishing my crates as mentioned in the issue linked above.

**Comment by alexcrichton** [comment]
Unfortunately I have no idea how this happens. Atomicity happens through `git push` (we don't use `-f`) so AFAIK that's like a compare-and-swap of the remote to a new HEAD. I could be wrong here though.

*If* a push is a compare-and-swap, then we should always gracefully handle situations like that in theory. If an index commit fails then the entire publish operation should be aborted and the relevant database transaction rolled back as well.

**Comment by seanmonstar** [comment]
Having dug into this today, here's what seems like is going on. The remote is reporting a failed push, which libgit2 will report back using the [`push_update_reference`](https://github.com/libgit2/libgit2/blob/75db289a041b1f1084768244e167b953ac7eeaa5/include/git2/remote.h#L441), but otherwise the `git push` operation reports success. That means crates.io won't notice, because the callback isn't set, and so it returns [here](https://github.com/rust-lang/crates.io/blob/master/src/git.rs#L140).

See https://github.com/libgit2/libgit2/issues/2628 for more.

**Comment by alexcrichton** [comment]
Thanks for the investigation @seanmonstar! I've bound that in https://github.com/rust-lang/crates.io/commit/7f731d4b5a48031ebb6b11503787e0f77a6f1998 and it's in the process of being deployed.

**Comment by alexcrichton** [comment]
I'm going to close this as suspected fixed, but we can keep our eyes peeled.
