### ISSUE TITLE
Remove Google Analytics and any other trackers from crates.io website

### ISSUE THREAD

**Issue by briansmith** [rust-lang/crates.io#460]
Currently https://crates.io/ has this:

``` html
<script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-58390457-3', 'auto');
      ga('send', 'pageview');
    </script>
```

Please remove this and other third-party tracking mechanisms, if any, from the crates.io website.

Lots of people working on Rust crates are privacy advocates like myself, trying to build privacy and/or anti-tracking tools. crates.io is basically a mandatory part of publishing Rust crates, because the design of the Rust ecosystem basically forces us to use it. This creates a conflict if crates.io itself uses the tracking mechanisms that we're working to protect people from.

**Comment by michael-zapata** [comment]
I second the request. Anti-tracking plugins are only effective for people already aware of the issue.

The issue is even bigger now, as badges usually have trackers.

**Comment by carols10cents** [comment]
I'd love PRs to add proxying of badges through the backend.

**Comment by carols10cents** [comment]
The core team discussed this- we occasionally use Google Analytics to inform decisions ([example](https://github.com/integer32llc/rfcs/blob/tiered-browser-support/text/0000-tiered-browser-support.md#google-analytics-browser-usage-stats)), and this is the easiest solution for us for now. We haven't researched self-hosted analytics gathering tools, so if someone would do that research and make some recommendations and PRs to add such a tool so that we could continue to get the data we need without going through a third party, we'd be open to that. 

Also, users have the workaround available of blocking third-party requests via browser extensions.

So I'm going to leave this open with a "help wanted" label for now, but it won't be a high priority unless we get that help.
