### ISSUE TITLE
Crate name collision

### ISSUE THREAD

**Issue by AloeareV** [rust-lang/crates.io#4780]
### Current Behavior

In the bip39 crate, version 1+ has a completely unrelated codebase from version 0.6-. They're two unrelated repos. There's no apparent connection between the two. https://crates.io/crates/bip39/versions

### Expected Behavior

There should be some indication that these are unconnected, or if they are connected it should be more obvious.

**Comment by Turbo87** [comment]
closing in favor of https://github.com/rust-bitcoin/rust-bip39/issues/22. if the author of the original crate decides to give away the name then that is their decision and it's up to them to signal that properly. since `1.0.0` is a major semver bump compared to `0.6.x` I don't think this is a major issue though.
