### ISSUE TITLE
Encoded URLs with a + sign fail

### ISSUE THREAD

**Issue by AngelloMaggio** [rust-lang/crates.io#4891]
Some clients, proxies, and/or repository managers may encode URLs to the upstream (for instance JFrog Artifactory). Due to blocks on crates.io some of these requests fail if there is a + sign in the URL

e.g. If we go to this URL it works fine:

https://static.crates.io/crates/libgit2-sys/libgit2-sys-0.12.25+1.3.0.crate

But if we go to the encoded URL it gives us a 403 Access Denied 
https://static.crates.io/crates/libgit2-sys/libgit2-sys-0.12.25%2B1.3.0.crate

This has also exposed some more strange behavior.
If we encode the + sign as a space (%20 instead of %2B), it works.
https://static.crates.io/crates/libgit2-sys/libgit2-sys-0.12.25%201.3.0.crate

Or even if I put a space instead in the URL (though that may be my browser encoding for me)
"https://static.crates.io/crates/libgit2-sys/libgit2-sys-0.12.25 1.3.0.crate" 

Since URL encoding is fairly standard and other encoding works, I believe this is a bug

**Comment by carols10cents** [comment]
`static.crates.io` goes to our s3 bucket. [The docs for s3 object names](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html) say:

> The following characters in a key name might require additional code handling and likely need to be URL encoded or referenced as HEX. 
> 
> ...
> - Plus ("+") 

So it looks like we should be URL encoding `+`. 

To fix this, we'll need to research whether we need to upload *both* URL encoded and unencoded for compatibility reasons or not...

**Comment by MaggioAngello** [comment]
Any update on this one? It's failing rust builds for us and wanted to see if there is any light at the end of the tunnel. Thank you so much! 
@carols10cents @Turbo87

**Comment by carols10cents** [comment]
Hi, yes, we talked about this in our most recent meeting but due to vacations and other projects, no one has the bandwidth to work on this immediately. If you have time to help, researching whether cargo can handle URLs using spaces returned from crates.io's `/download` redirects with or without encoding would be helpful. Thanks!

**Comment by ambassadorfunk** [comment]
@carols10cents - Are there any further updates on this issue and the timing of when the code fix will be merged? Thanks!

**Comment by carols10cents** [comment]
No, it needs to be reviewed and tested and no one has had time to do that yet.

**Comment by Turbo87** [comment]
Progress Update:

Step 1 of the proposed solution was implemented by #6649 and #6660. Step 2 was also fixed this morning. I'm now working on step 3.

**Comment by Turbo87** [comment]
Step 3 is being implemented by https://github.com/rust-lang/crates.io/pull/6665

@rust-lang/infra I will need your help on step 4 since I don't have access to the CDN infrastructure.

**Comment by jyn514** [comment]
@Turbo87 could you ask in the t-infra channel on Zulip, please? all of us get a *lot* of pings and it will be easier to coordinate the discussion.

(i don't have permissions to modify S3)

**Comment by Turbo87** [comment]
> Could you open an issue on rust-lang/cargo so that Cargo team can also track it?

done :)

(https://github.com/rust-lang/cargo/issues/12312)

**Comment by Turbo87** [comment]
https://github.com/rust-lang/simpleinfra/pull/313 has been merged and deployed this morning, which implements step 4 of the plan above.

https://github.com/rust-lang/crates.io/pull/6666 has subsequently been merged, which implements step 5 of the plan above. This PR will be deployed in the near future too.

The only thing remaining now is to remove all files from S3 that include a space character instead of the encoded `+` (step 6).
