### ISSUE TITLE
Send invalidations for index.crates.io when updating crates

### ISSUE THREAD

**Issue by arlosi** [rust-lang/crates.io#4913]
The HTTP index (index.crates.io) currently has a TTL of 10 minutes and does not send invalidations when publishing new crates. Users may need to wait up to 10 minutes after publishing a crate for it to be visible in the HTTP index.

If we sent invalidations to CloudFront when a crate was updated, we could increase the TTL (for better caching), and users would see updates sooner.

**Comment by alexcrichton** [comment]
To expand on my rationale for asking about this, I find this pretty crucial when publishing graph of crates all at once for the time being. When publishing a binary, even with `--no-verify` which doesn't compile anything, Cargo will (IIRC) generate a fresh `Cargo.lock` to get embedded into the `*.crate` file in case `cargo install --locked` is used. In this situation though the crates the binary depends on, if they live in the same repository, may not exist on crates.io yet. This round-trip time also naturally takes longer the deeper the dependency graph (although the deep case largely only matters for publishes that verify each step since otherwise the binary is typically only at the end).

Effectively I think a 10 minute TTL will make publishing a graph of crates infeasible. It's always possible for Cargo to use the git index on `cargo publish`, though (or perhaps with an opt-in).

**Comment by Eh2406** [comment]
That is a known issue. 10 minutes is not acceptable. Thanks for bringing this to our attention!
When we have invalidations the ttl should be way longer than 10 minutes, probably one day.
Before we have invalidations the ttl should be like 1 min. I will make a PR!
