### ISSUE TITLE
Most frequently searched keywords and/or in one week/month?

### ISSUE THREAD

**Issue by ghost** [rust-lang/crates.io#507]
And keywords should be could vote add by crates.io users(logged users?).

**Comment by carols10cents** [comment]
I'm not sure exactly what you mean-- what I think you're saying is that you'd like a page on crates.io that shows the search terms that people are entering most often in the search box on crates.io, possibly limited to the search terms used in the last week or month.

Or do you mean something to do with [the keywords feature](https://crates.io/keywords) of crates.io, the words that crate authors add to their crate's Cargo.toml to help people find their crate in searches?

For your second suggestion, what do you mean by "should be could vote add"? Can you give me an example of what a user would be voting for where? Are you saying that if a user searches for some term X, and doesn't find any crates that do X, that the user should be able to vote for X in order to show that people are looking for crates that do X? 

Or are you saying that for a particular crate, that users should be able to vote for a particular keyword to be added to that crate, so that that crate shows up higher in a list of crate search results if a future user types in that keyword?

Or something else? If you added an example of how someone would use the feature you're proposing, that would help a lot too! Thank you!!

**Comment by mindcat** [comment]
@carols10cents Sorry If I am confused you.
> what I think you're saying is that you'd like a page on crates.io that shows the search terms that people are entering most often in the search box on crates.io, possibly limited to the search terms used in the last week or month.
Yes.

> Or do you mean something to do with the keywords feature of crates.io, the words that crate authors add to their crate's Cargo.toml to help people find their crate in searches?
No, but that is interesting too.

> Are you saying that if a user searches for some term X, and doesn't find any crates that do X, that the user should be able to vote for X in order to show that people are looking for crates that do X?
Yes.

> Or are you saying that for a particular crate, that users should be able to vote for a particular keyword to be added to that crate, so that that crate shows up higher in a list of crate search results if a future user types in that keyword?
Yes.

You almost speak out my thought, Thanks you too.

**Comment by carols10cents** [comment]
I don't think we're going to do this.
