### ISSUE TITLE
"Owners" list on crates.io is misleading and should be renamed to "Release Managers"

### ISSUE THREAD

**Issue by nwalfield** [rust-lang/crates.io#5281]
### Current Behavior

On crates.io, each crate has a list of "owners".  Some people interpret the "owners" as being the primary authors of the crate, i.e., it's about attribution.  But, this is not how "owner" is actually used on crates.io.  It means "person authorized to make a release."  That is orthogonal to authorship.

### Expected Behavior

crates.io should rename the "owners" section to "release managers."  It would also be nice if crates.io included the list of authors (as extracted from the crates.io `Cargo.toml` file) to make attribution clearer.

### Environment

- Browser:
- OS:

**Comment by nwalfield** [comment]
Here's an example.  The sequoia-openpgp crates has three release managers, but [more authors](https://gitlab.com/sequoia-pgp/sequoia/-/blob/main/openpgp/Cargo.toml#L5).  For supply chain security reasons, we don't want to make all authors release managers.

![cratesio](https://user-images.githubusercontent.com/1164560/193794886-87222c24-c4ea-4cfd-a279-5d19af5a188f.png)

**Comment by Turbo87** [comment]
let's start with the easy bit:

> It would also be nice if crates.io included the list of authors (as extracted from the crates.io `Cargo.toml` file) to make attribution clearer.

the `authors` are explicitly not shown anymore (see https://rust-lang.github.io/rfcs/3052-optional-authors-field.html)

> On crates.io, each crate has a list of "owners". Some people interpret the "owners" as being the primary authors of the crate, i.e., it's about attribution.

You are right that a lot of people do conflate crate owners and authors, but that's also because for 95% of crates these groups of people are exactly the same. It is not meant as attribution though, and only shows which people have access to publish new versions of a crate. If you want to make the situation easier to understand you could create a "foobar release managers" GitHub team and give that access to publish releases instead of adding people individually.

Since our database and API calls these people owners and changing these terms would be a breaking change, it seems unlikely for us to rename this term to avoid unnecessary confusion.

**Comment by teythoon** [comment]
I'm sorry, but your response is not good enough.  Please re-open and discuss.

>>  On crates.io, each crate has a list of "owners". Some people interpret the "owners" as being the primary authors of the crate, i.e., it's about attribution.
>
> You are right that a lot of people do conflate crate owners and authors, but that's also because for 95% of crates these groups of people are exactly the same. It is not meant as attribution though, and only shows which people have access to publish new versions of a crate.

That's great for the 95% of these groups.  We have considerably more authors than we'd like to have owners, and this misunderstanding has torn our team apart.  I made the very same point you just made, that authorship and ownership is orthogonal, the response was that since crates.io only shows ownership, ownership equals attribution.

You are leaving us between a rock and a hard place:

- Either, we add all of our authors as owners.  This would enable all of them to upload new crates, and hence would weaken our supply chain security, and transitively that of the entire Rust ecosystem.
- Or, we only keep two people as owners, and risk alienating our authors.  This is the status quo, and it has a considerable and ongoing human cost.

> Since our database and API calls these people owners and changing these terms would be a breaking change, it seems unlikely for us to rename this term to avoid unnecessary confusion.

The term is already causing a lot of unnecessary confusion as you pointed out yourself.  And note that we are not asking to rename anything in the database or API.  There are at least two options that you seemingly didn't consider:

- Call it "release managers" or "uploaders" on the web site.
- Or, don't list the owners at all.

**Comment by teythoon** [comment]
I thought of more options:

- Introduce non-uploading owners that are displayed the same way as uploading owners.
- Let the owners specify the list of authors, and keep it up-to-date.  Display this list of authors (which is distinct from what Cargo.toml says, as to appease the concerns in 3052) instead of displaying the list of owners.

**Comment by carols10cents** [comment]
As a workaround, what about crediting the authors in your crate's README that crates.io displays?

**Comment by nwalfield** [comment]
I agree with @teythoon that it is not necessary to update the column names, etc.  I think the only place that would have to be changed is this one line: https://github.com/rust-lang/crates.io/blob/3eb66a51f0be920f0e40833a39904ab5cabe2187/app/components/crate-sidebar.hbs#L86 .  (Please correct me if I'm wrong.)

Relatedly, the ecosystem was largely able to move from `master` to `main`.  I think it we be good if we got rid of the term owner and moved towards more inclusive language.  In this case it is pretty easy: owner isn't even the right word for what is being denoted.

**Comment by teythoon** [comment]
It is not quite clear to me why that information should be displayed in the first place, i.e. what is the question it answers.  At first glance it seems to answer the question "whose machine do I have to compromise to upload a malicious crate with this name?".

**Comment by nwalfield** [comment]
Good point.  It is probably not about providing a point of contact, as that can usually better be derived from the README / documentation.  Perhaps the best solution is to just not show a crate's release managers on crates.io.
