### ISSUE TITLE
Sporadic deadlocks in production

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/crates.io#532]
Been noticing some errors in the logs these days:

```


Jan 29 21:00:47 crates-io app/web.1: ERROR:conduit_log_requests: 127.0.0.1:60753 [2017-01-30T05:00:47Z] Get /api/v1/crates/linux/0.0.0-rc/download - 3307ms 500: Error reported by Postgres Error reported by Postgres: ERROR: deadlock detected

Jan 29 21:11:51 crates-io app/web.2: ERROR:conduit_log_requests: 127.0.0.1:51238 [2017-01-30T05:11:51Z] Get /api/v1/crates/ntrumls/0.7.2/download - 1010ms 500: Error reported by Postgres Error reported by Postgres: ERROR: deadlock detected

Jan 29 21:11:52 crates-io app/web.1: ERROR:conduit_log_requests: 127.0.0.1:36997 [2017-01-30T05:11:52Z] Get /api/v1/crates/fixedvec/0.2.0/download - 1197ms 500: Error reported by Postgres Error reported by Postgres: ERROR: deadlock detected

Jan 29 21:11:53 crates-io app/web.2: ERROR:conduit_log_requests: 127.0.0.1:51333 [2017-01-30T05:11:53Z] Get /api/v1/crates/ntrumls/0.7.3/download - 1010ms 500: Error reported by Postgres Error reported by Postgres: ERROR: deadlock detected

Jan 29 21:11:54 crates-io app/web.2: ERROR:conduit_log_requests: 127.0.0.1:51354 [2017-01-30T05:11:54Z] Get /api/v1/crates/ntrumls/0.7.3/download - 1405ms 500: Error reported by Postgres Error reported by Postgres: ERROR: deadlock detected
```

cc @carols10cents 

(unfortunately no idea what caused this)

**Comment by carols10cents** [comment]
Yaaaaayyy fun times. Will look into this soon.

**Comment by tef** [comment]
I casually mentioned this on twitter but I figure it's worth repeating here: Deadlocks are kinda normal in databases.

You can't really avoid deadlocks in a transactional locking system: There isn't a nice "get all the keys in this order" way to do it, and so yeah, postgres has to break the cycles when two transactions end up blocking each other. In an optimistic system, you'd see aborts instead of deadlocks when two transactions collide.

Getting rid of the deadlock is going to be worthwhile if you're seeing performance problems related to contention. Or, a long running transaction keeps getting killed.

One of the things that stands out here is that the deadlocked transactions are a couple of seconds old. If you can turn on logging for long running transactions, you might have a bit more of a thread to pull on.

**Comment by alexcrichton** [comment]
Thanks for the info @tef! This may just be a case that we don't worry about as it happens pretty rarely anyway

**Comment by sgrif** [comment]
I think this is resolved. The only deadlock in our logs for the last week happened in `bin/update-downloads`, and that should have been fixed by https://github.com/rust-lang/crates.io/pull/1345
