### ISSUE TITLE
Nightly build broke

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#546]
Not entirely sure why because the PRs all passed, but i'll look into it tonight.

https://travis-ci.org/rust-lang/crates.io/builds/198708315

**Comment by LeopoldArkham** [comment]
It looks like the only problem is that the DB is updated from a hashmap with no fixed order, but the failing test makes a comparison with a fixed-order `Vec`. The test on the PR probably got lucky on the order, since there are only two elements!

Maybe @Susurrus can look into this, just testing with `.contains()` should do it!
