### ISSUE TITLE
Old versions of cargo cannot install any version of a crate that has a version with a prelease string

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#584]
Related to #580 and rust-lang/cargo#3763.

With Cargo 0.8 (shipped with Rust 1.7) and earlier, version numbers that include things like `-rc` or `-alpha` can't be parsed.

Furthermore, Cargo 0.8 can't install *any* version of any crate that has any version number like that, even if you're not trying to use those particular versions.

I'm not sure exactly what the issue with crates.io's API is, and if it's possible to fix or not, but I think we should investigate it and see if there's a way we could change crates.io's API to allow older versions of cargo to continue to be able to install crates that happen to have some version like this.

**Comment by alexcrichton** [comment]
I unfortunately don't believe there's anything we can do here. The problem lies in the index itself which lists all versions. Cargo will parse the entire file related to a crate (e.g. parse all versions of a crate). This means that if historical Cargo attempts to look at a crate with a "bad version" then it will generate an error.

The only real fix here for historical Cargo is to outright delete the entries from the index, which likely isn't tenable.

**Comment by carols10cents** [comment]
Closing as wontfix then
