### ISSUE TITLE
Recheck Mozilla's Observatory after #586 is fixed

### ISSUE THREAD

**Issue by elliotekj** [rust-lang/crates.io#585]
Crates currently scores 15/100 in [Mozilla’s Obervatory](https://observatory.mozilla.org/analyze.html?host=crates.io). I’m not familiar enough with the codebase to know how many of these policies can’t be implemented for a technical reason, but it seems like Crates could be doing better. For comparison, [NPM scores 75/100](https://observatory.mozilla.org/analyze.html?host=npmjs.com) and [rubygems scores 50/100](https://observatory.mozilla.org/analyze.html?host=rubygems.org).

**Comment by Insomgla** [comment]
I think most issues here are rather easy to fix, so it should be worth it.

**Comment by carols10cents** [comment]
I think this is worth fixing, but I'm not familiar with these headers or their implications. crates.io is hosted on heroku so we don't really control the web server config.

It looks like rails apps (lots of which are hosted on heroku) just add the CSP header in the application, so that should be fine (https://github.com/blog/1477-content-security-policy)

I'd love if someone could turn each of the tasks into an issue, or at least a checklist in this issue, so we can track who's working on what and what is done or not, and discuss any issues/implications!

**Comment by alexcrichton** [comment]
Oh FWIW we do have [some control of a frontend server](https://github.com/rust-lang/crates.io/blob/master/config/nginx.conf.erb) and we should also be able to set headers ourselves through middleware and such.

**Comment by carols10cents** [comment]
Thank you for making #586 with a checklist for all the headers, @Insomgla! I've changed the title of this one to check how we're doing after those get taken care of.

**Comment by carols10cents** [comment]
As mentioned in https://github.com/rust-lang/crates.io/pull/597, crates.io now gets an A-! Closing!
