### ISSUE TITLE
README.md not updated on 

### ISSUE THREAD

**Issue by yagitatsu** [rust-lang/crates.io#6095]
### Current Behavior

When main or master branch on the repository has updated, README.md seems to be updated on crates.io.
For example: 

- crates.io: https://crates.io/crates/plotters
- github: https://github.com/plotters-rs/plotters

### Expected Behavior

Two of README.md should be the same.
When README.md is wrong, I think it can be updated without tagging.

### Environment

- Browser:
- OS:

**Comment by Turbo87** [comment]
the README file is taken and rendered from the published crates, not from the repository. the reason for that is that it should match the version with which it was released. otherwise we would end up with documentation that might not match the APIs of the released versions.

in other words: if you want to update the README that is shown on crates.io you will have to release a new version.
