### ISSUE TITLE
Show latest stable version on search result page

### ISSUE THREAD

**Issue by badboy** [rust-lang/crates.io#654]
Currently it seems to show the latest released version, even if it is a pre-release.

Example: https://crates.io/search?q=bincode
I see: bincode v1.0.0-alpha6

Following the link I get to `bincode v0.6.1`

It should show v0.6.1 on the search page as well.

**Comment by carols10cents** [comment]
Thank you! This is related to, but slightly different from, #510.

**Comment by briansmith** [comment]
Not sure if this is the same thing, but pages like https://crates.io/categories/cryptography also show prerelease (e.g. alpha) versions instead of showing the latest stable version.

**Comment by Turbo87** [comment]
I just had a quick look at this as it was labeled "A-ember". The problem is that from the API we only get `max_version` (highest version; semver order) and `newest_version` (the most recently updated version), but both include prereleases. I guess this would need to be changed on the API side, so that `max_version` only considers regular releases, but not prereleases. Unfortunately, I can't judge whether that might break anything else... 😞
