### ISSUE TITLE
Crate publishing failing

### ISSUE THREAD

**Issue by epage** [rust-lang/crates.io#6854]
### Current Behavior

publishing 0.0.8 and 0.0.9 of `completest` times out in cargo

### Expected Behavior

publish succeeds

### Steps To Reproduce

```console
$ git clone https://github.com/assert-rs/completest
$ cd completest
$ cargo release patch -v -x
```

### Environment

- Browser:  Firefox
- OS:PopOS 22.04

### Anything else?

See 
- https://crates.io/crates/completest/0.0.8
 - https://crates.io/crates/completest/0.0.9

The README is also not showing up.

**Comment by epage** [comment]
README still isn't there but it is now available for me to use.

**Comment by Turbo87** [comment]
this was most likely related to https://status.crates.io/incidents/34038dqnh1f4, which happened roughly in the same timeframe. the short version is: our background worker queue got overwhelmed and so the syncs to the indexes took longer than usual. things should be back to normal now.

since https://github.com/rust-lang/crates.io-index/blob/master/co/mp/completest is showing the versions and the READMEs have also been rendered by now I'll close this issue :)
