### ISSUE TITLE
Clear communication on crates.io hosting

### ISSUE THREAD

**Issue by mrwunderbar666** [rust-lang/crates.io#6994]
Dear Crates.io team,

I need to provide some context first. 

CRAN (the package hosting service for R) recently changed its policy on packages that use Rust libraries. Some of these changes cause trouble for R + Rust developers. The most pressing change is that R packages which use Rust libraries must now include all their dependencies (which inflates the size of the R package). The reasoning is the stated [here](https://cran.r-project.org/web/packages/using_rust.html), and here is the relevent excerpt (emphasis added):

> Downloading should be avoided if at all possible. The package would become uninstallable if the Internet resources are temporarily or permanently unavailable, and CRAN packages are kept available for many years. **CRAN does not regard github.com (which hosts the index of crates.io and many of the crates) as sufficiently reliable**.

> In most cases all the Rust software can be bundled into the package via cargo vendor. [ ... ] If the bundle is too large to be included in the package sources, **it could be hosted at a long-term secure site under the maintainer’s control**.

I was looking into that statement that crates.io was hosted on github, but I could not find clear information about this on crates.io (maybe I missed it).

As far as I know, crates.io has its crate index *mirrored* on github (for practical reasons), but maintains its own index (that is hosted on an AWS server?).

In order to liason with the CRAN maintainers, it would be helpful if you could provide a clearer statement about the "reliability" of crates.io (i.e., that CRAN does not have to worry about crates.io going down and will be lost without any chance being retrieved).

Thanks and kind regards

**Comment by Eh2406** [comment]
> As far as I know, crates.io has its crate index mirrored on github (for practical reasons), but maintains its own index (that is hosted on an AWS server?).

History is a little more complicated than this summary. Until fairly recently cargo downloaded and used the copy from GitHub. With the new "sparse index" protocol the official source of truth has moved to a website run exclusively by crates.io and posted on S3.

To be clear the index is now on the same infrastructure as the crate downloads. The crate downloads were not objected to in the linked document.

> In order to liason with the CRAN maintainers, it would be helpful if you could provide a clearer statement about the "reliability" of crates.io (i.e., that CRAN does not have to worry about crates.io going down and will be lost without any chance being retrieved).

We (technically the Rust Foundation and the crates.io Team) promise to keep it up to the best of our ability. It will be kept it as immutable as legally possible. The future is hard to predict, and CRAN can feel free to not believe us.

Thanks to the mirror on GitHub it is easy to maintain a mirror on whatever hosting service you wish.

**Comment by mrwunderbar666** [comment]
Thanks for the replies and clarifications.

> We (technically the Rust Foundation and the crates.io Team) promise to keep it up to the best of our ability. It will be kept it as immutable as legally possible. The future is hard to predict, and CRAN can feel free to not believe us.

I think this is a very good statement, thank you for that. 

Do you think, it would be possible to show a list of official and inofficial mirrors on crates.io?

**Comment by LawnGnome** [comment]
> Do you think, it would be possible to show a list of official and inofficial mirrors on crates.io?

We (speaking for the crates.io team) don't have any current plans to support mirroring[^mirroring] — crates.io (and, by extension, index.crates.io and static.crates.io) is the authoritative source for the sparse[^sparse] crate index and crate files. As @Eh2406 said, for the index and crate files, that's basically just S3 with a mixture of Fastly and CloudFront in front of it.

What @Eh2406 is saying is that CRAN could, in theory, maintain its own mirror of the crates.io index for older Rust versions that rely on GitHub for the legacy index if they are concerned about GitHub's reliability. I personally wouldn't recommend it, though! And, of course, this wouldn't address the other concern in the CRAN policy around internet connectivity in general; `cargo vendor`, as suggested, is the only realistic solution to that, since the Rust toolchain generally expects to have internet access available in the non-vendored case.

Given that, I don't see an obvious change we could make here, besides endorsing @Eh2406's statement on keeping the lights on as best we can. :slightly_smiling_face: 

[^mirroring]: I _personally_ have discussed mirroring crates.io a little, but in the context of helping users behind restrictive firewalls (for example, in repressive regimes) be better able to use Rust, rather than for reliability purposes. There are a number of things that have to happen before even that level of mirroring is possible in a secure way, though, and I don't expect any movement there for several months, at least.
[^sparse]: The sparse index is used by default in Rust ≥ 1.70.0.

**Comment by LawnGnome** [comment]
Drifting well off topic, obviously, but:

> I could imagine something like https://ipfs.tech/ or crates.io hosted on Tor and having connecting via [arti](https://gitlab.torproject.org/tpo/core/arti).

Yep, both IPFS and Tor are things I'm explicitly considering here, besides good old fashioned HTTP mirrors.
