### ISSUE TITLE
Confusing error for invalid feature names

### ISSUE THREAD

**Issue by Boddlnagg** [rust-lang/crates.io#7250]
I just tried to publish a crate containing features with names that have dots in them (see e.g. [here](https://github.com/contextfree/winrt-rust/blob/3ec231209a224edc92e913cf3fab1a3aa0e7d454/Cargo.toml)).
On `cargo publish` I got the following: `api errors: invalid upload request: ApplicationError("invalid crate name specified: windows.web")`, and there are actually several issues:
1. The message confusingly complains about the _crate_ name
2. It should complain earlier, not on `publish`, when you think that everything should work
3. Is there a good reason that dots are not allowed?

By the way this also affects @retep998's 0.3 rewrite of winapi, where I originally got the idea for these features names: https://github.com/retep998/winapi-rs/blob/dev/Cargo.toml

**Comment by Turbo87** [comment]
interesting, I just read through https://doc.rust-lang.org/cargo/reference/features.html#the-features-section and I wasn't aware that we had restrictions on feature names that only apply to the crates.io side. I was under the impression that the same restrictions existed on the cargo side too.

I'm open to lifting some of these restrictions, but we will first need to find out why they exist in the first place so that we don't accidentally break something. if anyone feels like working on this, you are very welcome to help figure this out. git blame will likely give a few hints :)

RE the error message: this had been fixed quite some time ago already. it now warns about the feature name not being valid. though I guess we could give some more context with a link to the docs or something like that.

I agree with @epage that clientside validation by cargo could be tricky with the different format restrictions.

**Comment by hi-rustin** [comment]
I went through the git history, I think we don't have a special reason to refuse `.` in the feature name.
1. We introduced the basic check in this PR. Called  `name_to_slug` https://github.com/rust-lang/crates.io/commit/45131f36dc371b50559fa2a85df3a63da5d25b74
2. We renamed it to `valid_name`. https://github.com/rust-lang/crates.io/commit/89c407977bee6377c9b47996749a60bb268f6c79
3. We added support for `/` in the feature name. https://github.com/rust-lang/crates.io/commit/d64528f9e9218bb1152b93a9b5e88e735044762e
4. We allowed feature names to begin with numbers. https://github.com/rust-lang/crates.io/commit/4bf9efa4af7421d4b3d04553437fc35c403ff87b
5. We added support for `+` in the feature name. https://github.com/rust-lang/crates.io/commit/5f842f73c6a9f32719508db4b1c534959b02f6e8

So I think there is no reason to refuse `.` in the feature name. I will try to add and test it.

**Comment by hi-rustin** [comment]
Fixed by https://github.com/rust-lang/crates.io/pull/7500
