### ISSUE TITLE
Add an EULA/Terms of Service

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/crates.io#749]
At a minimum `crates.io` should be requesting a license allowing it to host and re-publish users code to ensure no one can claim that it's doing that without a license (or that by doing so `crates.io` is violating some terms of whatever license they provided). A nice example is from the [`npm` EULA](https://www.npmjs.com/policies/open-source-terms#your-content):

> Your Content belongs to you. You decide whether and how to license it. But at a minimum, you license npm to provide Your Content to users of npm Services when you share Your Content. That special license allows npm to copy, publish, and analyze Your Content, and to share its analyses with others. npm may run computer code in Your Content to analyze it, but npm's special license alone does not give npm the right to run code for its functionality in npm products or services.

(Forked from https://github.com/rust-lang/crates.io/issues/736#issuecomment-306203298)

**Comment by azastrael** [comment]
Hey :wave:!

I know this issue is over 2 years old but since #955 has been (relatively) recently closed and the use of crates.io seems to be exploding (shared by @alexcrichton on discord: https://docs.google.com/spreadsheets/d/1VozV1fwz4bgRlPwhkCDHTqwBeHHCH1-QL4yh47EPpVg/edit#gid=1373479972) , maybe now is the time to take care of it.

The example, given in the opening comments, of `npm`'s policies is actually opensource (https://github.com/npm/policies), so this could be adapted for crates.io. Or maybe, since it was stated in #955 that team members were in contact with lawyers at the time, those same lawyers could help with this.

Whatever the way chosen to do this is, it is pretty important to insure that the registry doesn't face the possibility of users claiming copyright or license violations as soon as possible.

Cheers! :)

**Comment by Turbo87** [comment]
https://github.com/rust-lang/rfcs/pull/3463 has been opened to address some of this :)
