### ISSUE TITLE
Dark mode missing avatar background

### ISSUE THREAD

**Issue by AuracleTech** [rust-lang/crates.io#8708]
### Current Behavior

White background on avatars

![image](https://github.com/rust-lang/crates.io/assets/40531871/2092ad25-fbaf-40aa-a796-476e94463e89)

### Expected Behavior

Dark background on avatars

![image](https://github.com/rust-lang/crates.io/assets/40531871/dd7b0c58-4e6c-4fce-b89d-8de81a5a929c)

### Steps To Reproduce

N/A

### Environment

N/A

### Anything else?

Small issue, quick fix

**Comment by Turbo87** [comment]
<img width="158" alt="Bildschirmfoto 2024-05-23 um 21 25 58" src="https://github.com/rust-lang/crates.io/assets/141300/e3d44697-0888-464a-a5e9-a6401304ad2c">

<img width="422" alt="Bildschirmfoto 2024-05-23 um 21 26 23" src="https://github.com/rust-lang/crates.io/assets/141300/3e600005-0a33-4986-91e1-e8ed12dcc78c">


this is not a bug of our dark mode, and looking at GitHub this does not appear to be a bug in our avatar rendering either. you might want to give your avatar a proper background instead of using white on transparent 😉

**Comment by AuracleTech** [comment]
Its white on in white mode
And white in dark mode

And I'm wrong? sure
