### ISSUE TITLE
Frontend recreates dist/ directory even when it exists

### ISSUE THREAD

**Issue by vignesh-sankaran** [rust-lang/crates.io#934]
Uploading a crate locally results in the `dist/` directory being created with the crate available. However, when I run the frontend, it deletes the directory and recreates it, thus removing the uploaded crate. This is a problem specific to macOS so far.

**Comment by kureuil** [comment]
Yeah, this behavior is not specific to macOS I also encountered it on Linux, it is ember-cli's way of doing things apparently. Each time the front-end application is modified, it deletes the dist folder and regenerates it with the newly compiled files, removing any locally uploaded crates.

See also https://github.com/rust-lang/crates.io/issues/734#issuecomment-302874950

**Comment by vignesh-sankaran** [comment]
Yep, I'm going to work on this, I'm a bit worried we're storing local crates in a folder that is recreated every time the frontend is run again :).

**Comment by carols10cents** [comment]
So in one sense this is a bug, in that you've "published" and "uploaded" the crate and it's in your database, but the files are removed, and that's unexpected.

In another sense, we're, uh, "saving disk space". You won't have huge files sitting around from testing out publishing.

I'm open to changing this behavior; I think the documentation should be improved along with a change to say "locally uploaded crate files end up in `whatever/directory`. If you don't care about keeping uploaded crate files in order to enable downloading of those crates, feel free to remove these files or delete the whole directory periodically to save on disk space" or something similar.
