### ISSUE TITLE
Cannot report a crate

### ISSUE THREAD

**Issue by trueb2** [rust-lang/crates.io#9683]
### Current Behavior

Clicking report issue opens the native mail app instead of submitting the report. 

![Image](https://github.com/user-attachments/assets/5e54fc08-cd06-4c8d-862a-e18bc26e2304)

![Image](https://github.com/user-attachments/assets/d75d509a-e1ac-4a14-a835-a84aaab80367)

### Expected Behavior

I don't use the native mail app, and it should never be triggered by crates.io, especially when signed in. It makes it impossible to report a crate.

### Steps To Reproduce

In Safari on MacOS:

go to a crate.
fill in content for reporting a crate. 
click report.

### Environment

- Browser: Safari 18.0
- OS: macOS 15.0

**Comment by Turbo87** [comment]
what are you using instead of the native app? most operating systems have a way of configuring what app is opened when mailto links are used, and AFAIK the same is possible for e.g. GMail in the browser.

we are unlikely to change this implementation in the near future since we would have to use a commercial email service for this, and that runs the risk of people abusing it and us having to pay the bill for it.

if you can't use the form you can always directly send emails to help@crates.io
