### ISSUE TITLE
Markdown README rendering doesn't handle checkbox lists

### ISSUE THREAD

**Issue by jwilm** [rust-lang/crates.io#978]
Rendering markdown like

```md
- [ ] foo
- [x] bar
```

Should be generate a series of checkboxes, like so:

- [ ] foo
- [x] bar

However, this is what we see on crates.io:

![image](https://user-images.githubusercontent.com/4285147/29490074-3bb0eff2-84e6-11e7-9f7f-4ca751276dbc.png)

Here's a crate/version exhibiting the issue: https://crates.io/crates/postgres-cursor/0.2.2

**Comment by anthonynguyen** [comment]
Turns out [pulldown-cmark] only implements the CommonMark spec, so it doesn't have GFM features like task lists. I've found another Markdown renderer, [comrak], that has task lists, and it's pretty trivial to switch to it. Unfortunately, there's an issue (https://github.com/kivikakk/comrak/issues/32) that would prevent it from rendering *your* Markdown properly, but it'd still be better than right now.

[pulldown-cmark]: https://github.com/google/pulldown-cmark
[comrak]: https://github.com/kivikakk/comrak

**Comment by carols10cents** [comment]
This has been fixed by https://github.com/rust-lang/crates.io/pull/981!
