### ISSUE TITLE
Improve conduit documentation or move out of it?

### ISSUE THREAD

**Issue by mauricio** [rust-lang/crates.io#994]
Conduit doesn't have much docs and this makes it harder to try and figure out what's going on in the repo, to make it easier for people to contribute it would be nice if we could either improve conduit as well or maybe use some other framework like iron?

**Comment by carols10cents** [comment]
I'm not opposed to changing frameworks, but it is rather risky, and I'd want to see if we could migrate in small, deployable pieces. Also the web framework space in Rust feels rather exploratory at the moment-- I don't know enough to choose between iron, nickel, rocket, gotham, cargonauts, etc. 

So for the moment, since crates.io is a functioning production service that I don't want to break lightly, I think we should focus on improving the documentation for crates.io and/or conduit. Please feel free to open another issue if you have any specific questions on how we're using conduit here!
